# Generated by manage.py generate_test_cases.
from bloomerp.models.llm.ai_conversation import AIConversation
from bloomerp.tests.base import BloomerpModelTestCase


class TestAiconversationModel(BloomerpModelTestCase):
    model = AIConversation
