# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestDocumentTemplateListDetailView(BloomerpDetailViewTestCase):
    view_name = 'document_templates'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
