# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestForeignRelationshipView(BloomerpDetailViewTestCase):
    """Tests class `ForeignRelationshipView` from `bloomerp/views/generic/detail/foreign_relationship.py`."""

    view_name = 'manufacturingorder_set_relationship'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
