# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpDetailFileListView(BloomerpDetailViewTestCase):
    """Tests class `BloomerpDetailFileListView` from `bloomerp/views/generic/detail/files.py`."""

    view_name = 'files'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
