# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestForeignRelationshipView(BloomerpDetailViewTestCase):
    view_name = 'manufacturingorder_set_relationship'
    model = None

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
