# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestBloomerpDeleteView(BloomerpDetailViewTestCase):
    view_name = 'delete'
    model = None

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
