# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestActivityLogComponent(BloomerpComponentTestCase):
    """Tests function `activity_log` from `bloomerp/components/activity/activity_log.py`."""

    view_name = 'components_activity_log'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
