# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestActivityLogComponent(BloomerpComponentTestCase):
    view_name = 'components_activity_log'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
