# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestApproveWorkflowContinuationComponent(BloomerpComponentTestCase):
    """Tests function `approve_workflow_continuation` from `bloomerp/components/automation/approve_workflow_continuation.py`."""

    view_name = 'components_automation_approve_workflow_continuation'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
