# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSaveWorkflowComponent(BloomerpComponentTestCase):
    """Tests function `save_workflow` from `bloomerp/components/automation/save_workflow.py`."""

    view_name = 'components_automation_save_workflow'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
