# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRunWorkflowComponent(BloomerpComponentTestCase):
    """Tests function `run_workflow` from `bloomerp/components/automation/run_workflow.py`."""

    view_name = 'components_automation_run_workflow'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
