# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenderWorkflowNodeSchemaPanelComponent(BloomerpComponentTestCase):
    """Tests function `render_workflow_node_schema_panel` from `bloomerp/components/automation/render_workflow_node.py`."""

    view_name = 'components_automation_render_workflow_node_schema_panel'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
