# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenderAutomationDrawerComponent(BloomerpComponentTestCase):
    """Tests function `render_automation_drawer` from `bloomerp/components/automation/drawer.py`."""

    view_name = 'components_automation_drawer'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
