# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestRenderAutomationDrawerComponent(BloomerpComponentTestCase):
    view_name = 'components_automation_drawer'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
