# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestSaveWorkflowComponent(BloomerpComponentTestCase):
    view_name = 'components_automation_save_workflow'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
