# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestRenderWorkflowNodeComponent(BloomerpComponentTestCase):
    view_name = 'components_automation_render_workflow_node'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
