from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    E2EAction,
    E2ERequestSetup,
)
from bloomerp.tests.base import e2e_test_case as e2e_test_cases


class TestDetailViewE2E(e2e_test_cases.BloomerpE2ETestCase):
    def get_request_setups(self) -> list[E2ERequestSetup]:
        todo = Todo.objects.create(title="Hello world")

        return [
            E2ERequestSetup(
                name="Admin updates an autogenerated field",
                user=self.admin_user,
                url=todo.get_absolute_url(),
                actions=[
                    E2EAction(
                        name="Change the title",
                        execute=self.input_field("title", "Hello world 2"),
                        validators=[
                            self.expect_field_value(
                                "title",
                                "Hello world 2",
                            ),
                        ],
                    ),
                    E2EAction(
                        name="Save the todo",
                        execute=self.press_button_and_wait_for_response(
                            "Save",
                            todo.get_absolute_url(),
                            method="POST",
                        ),
                        validators=[
                            self.expect_database_value(
                                todo,
                                "title",
                                "Hello world 2",
                        ),
                            self.expect_text("Updated succesfully")
                        ],
                    ),
                ],
            ),
            E2ERequestSetup(
                name="Admin  can add fields",
                user=self.admin_user,
                url=todo.get_absolute_url(),
                actions=[
                    E2EAction(
                        execute=self.press_button(
                            "Edit"
                        ),
                        validators=[
                            self.expect_visible()
                        ]
                    )
                ]
                
            )
        ]
