# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestFilesComponent(BloomerpComponentTestCase):
    """Tests function `files` from `bloomerp/components/files.py`."""

    view_name = 'components_files'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
