# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestExecuteSqlQueryComponent(BloomerpComponentTestCase):
    view_name = 'components_execute_sql_query'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
