# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestDetailTabsItemModalComponent(BloomerpComponentTestCase):
    view_name = 'components_detail_tabs_item_modal'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
