# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDetailTabsPreferenceComponent(BloomerpComponentTestCase):
    """Tests function `detail_tabs_preference` from `bloomerp/components/detail_tabs_preference.py`."""

    view_name = 'components_detail_tabs_preference'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
