# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestPreviewWorkspaceTileComponent(BloomerpComponentTestCase):
    view_name = 'preview_workspace_tile'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
