# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestPreviewWorkspaceTileComponent(BloomerpComponentTestCase):
    """Tests class `PreviewWorkspaceTile` from `bloomerp/components/workspaces/preview_workspace_tile.py`."""

    view_name = 'preview_workspace_tile'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
