# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDeleteWorkspaceComponent(BloomerpComponentTestCase):
    """Tests function `delete_workspace` from `bloomerp/components/workspaces/delete_workspace.py`."""

    view_name = 'components_workspaces_delete_workspace'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
