# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestSidebarSetSelectedComponent(BloomerpComponentTestCase):
    view_name = 'components_workspaces_sidebar_set_selected'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
