# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSidebarDeleteComponent(BloomerpComponentTestCase):
    """Tests function `sidebar_delete` from `bloomerp/components/workspaces/sidebar.py`."""

    view_name = 'components_workspaces_sidebar_delete'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
