# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestShareWorkspaceComponent(BloomerpComponentTestCase):
    view_name = 'components_workspaces_share_workspace'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
