# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestWorkspaceFiltersValueInputComponent(BloomerpComponentTestCase):
    view_name = 'components_workspaces_filters_value_input'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
