# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestSidebarCreateLinkFromDropComponent(BloomerpComponentTestCase):
    view_name = 'components_workspaces_sidebar_create_link_from_drop'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
