# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestInitialDataComponent(BloomerpComponentTestCase):
    """Tests function `initial_data` from `bloomerp/components/forms/initial_data.py`."""

    view_name = 'components_forms_initial_data'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
