# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestQrCodeComponent(BloomerpComponentTestCase):
    """Tests function `qr_code` from `bloomerp/components/forms/qr_code.py`."""

    view_name = 'components_forms_qr_code'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
