# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestInitialDataComponent(BloomerpComponentTestCase):
    view_name = 'components_forms_initial_data'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
