# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestQrCodeComponent(BloomerpComponentTestCase):
    view_name = 'components_forms_qr_code'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
