# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestAccessibleTablesView(BloomerpAPIViewTestCase):
    """Tests class `AccessibleTablesView` from `bloomerp/views/api/sql/accessible_tables.py`."""

    view_name = 'api_sql_accessible_tables'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
