# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestExecuteSqlView(BloomerpAPIViewTestCase):
    """Tests class `ExecuteSqlView` from `bloomerp/views/api/sql/execute.py`."""

    view_name = 'api_sql_execute'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
