# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpViewTestCase


class TestAccessibleTablesView(BloomerpViewTestCase):
    view_name = 'api_sql_accessible_tables'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
