# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestBloomerpProfilePasswordResetView(BloomerpDetailViewTestCase):
    view_name = 'reset_password'
    model = User

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
