# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestUserCreateView(BloomerpModelViewTestCase):
    """Tests class `UserCreateView` from `bloomerp/views/users/create.py`."""

    view_name = 'add'
    model = User

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
