# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpProfilePasswordResetView(BloomerpDetailViewTestCase):
    """Tests class `BloomerpProfilePasswordResetView` from `bloomerp/views/users/reset_password.py`."""

    view_name = 'reset_password'
    model = User

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
