# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpProfileView(BloomerpModelViewTestCase):
    """Tests class `BloomerpProfileView` from `bloomerp/views/users/profile.py`."""

    view_name = 'my_profile_overview'
    model = User

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
