# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import BloomerpModelViewTestCase


class TestUserCreateView(BloomerpModelViewTestCase):
    view_name = 'add'
    model = User

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
