# Generated by manage.py generate_test_cases.
from bloomerp.models.files.file_folder import FileFolder
from bloomerp.tests.base import BloomerpModelTestCase


class TestFileFolderModel(BloomerpModelTestCase):
    model = FileFolder
