# Generated by manage.py generate_test_cases.
from bloomerp.models.files.file import File
from bloomerp.tests.base import BloomerpModelTestCase


class TestFileModel(BloomerpModelTestCase):
    model = File
