# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template import DocumentTemplate
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestDocumentTemplateGenerateView(BloomerpDetailViewTestCase):
    view_name = 'Generate PDF'
    model = DocumentTemplate

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
