# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template import DocumentTemplate
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestDocumentTemplateBuilderEditView(BloomerpDetailViewTestCase):
    view_name = 'builder'
    model = DocumentTemplate

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
