# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template import DocumentTemplate
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestDocumentTemplateBuilderEditView(BloomerpDetailViewTestCase):
    """Tests class `DocumentTemplateBuilderEditView` from `bloomerp/views/document_templates/document_template_builder_view.py`."""

    view_name = 'builder'
    model = DocumentTemplate

    def create_test_object(self):
        return DocumentTemplate.objects.create(
            name="A name"
        )
    
    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return [
            RequestSetup(
                name="View loads normally",
                method="GET",
                user=self.admin_user,
            )
        ]
