# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestExportObjectsComponent(BloomerpComponentTestCase):
    """Tests function `export_objects` from `bloomerp/components/objects/export.py`."""

    view_name = 'components_export_objects'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
