# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestExportObjectsComponent(BloomerpComponentTestCase):
    view_name = 'components_export_objects'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
