# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSearchObjectsComponent(BloomerpComponentTestCase):
    """Tests function `search_objects` from `bloomerp/components/objects/search_objects.py`."""

    view_name = 'components_search_objects'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
