# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestObjectPreviewComponent(BloomerpComponentTestCase):
    view_name = 'components_object_preview'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
