# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestFieldDisplayOptionsComponent(BloomerpComponentTestCase):
    view_name = 'components_field_display_options'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
