# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestActionsExecuteComponent(BloomerpComponentTestCase):
    """Tests function `actions_execute` from `bloomerp/components/objects/actions.py`."""

    view_name = 'components_objects_actions'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
