# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestObjectPreviewComponent(BloomerpComponentTestCase):
    """Tests function `object_preview` from `bloomerp/components/objects/object_preview.py`."""

    view_name = 'components_object_preview'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
