# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateObjectComponentViewComponent(BloomerpComponentTestCase):
    """Tests class `CreateObjectComponentView` from `bloomerp/components/objects/crud_object.py`."""

    view_name = 'components_create_object'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
