# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.user_inbox_preference import UserInboxPreference
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserInboxPreferenceModel(BloomerpModelTestCase):
    model = UserInboxPreference
