# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.inbox_folder import InboxFolder
from bloomerp.tests.base import BloomerpModelTestCase


class TestInboxFolderModel(BloomerpModelTestCase):
    model = InboxFolder
