# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.inbox import Inbox
from bloomerp.tests.base import BloomerpModelTestCase


class TestInboxModel(BloomerpModelTestCase):
    model = Inbox
