# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.inbox.inbox_item import InboxItem
from bloomerp.tests.base import BloomerpModelTestCase


class TestInboxItemModel(BloomerpModelTestCase):
    model = InboxItem
