# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.phone_number_field import PhoneNumberField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestPhoneNumberField(BloomerpModelFieldTestCase):
    field_class = PhoneNumberField
