# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.week_field import WeekField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestWeekField(BloomerpModelFieldTestCase):
    field_class = WeekField
