# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.text_editor_field import TextEditorField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestTextEditorField(BloomerpModelFieldTestCase):
    field_class = TextEditorField
