# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.code_field import CodeField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestCodeField(BloomerpModelFieldTestCase):
    field_class = CodeField
