# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.one_to_one_user_field import OneToOneUserField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestOneToOneUserField(BloomerpModelFieldTestCase):
    field_class = OneToOneUserField
