# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.address_field import AddressField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestAddressField(BloomerpModelFieldTestCase):
    field_class = AddressField
