# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.status_field import StatusField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestStatusField(BloomerpModelFieldTestCase):
    field_class = StatusField
