# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.user_field import UserField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestUserField(BloomerpModelFieldTestCase):
    field_class = UserField
