# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.file_field import BloomerpFileField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestBloomerpFileField(BloomerpModelFieldTestCase):
    field_class = BloomerpFileField
