# Generated by manage.py generate_test_cases.
from bloomerp.model_fields.icon_field import IconField
from bloomerp.tests.base import BloomerpModelFieldTestCase


class TestIconField(BloomerpModelFieldTestCase):
    field_class = IconField
