# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user_object_layout_preference import UserObjectLayoutPreference
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserObjectLayoutPreferenceModel(BloomerpModelTestCase):
    model = UserObjectLayoutPreference
