# Generated by manage.py generate_test_cases.
from bloomerp.models.users.bookmark import Bookmark
from bloomerp.tests.base import BloomerpModelTestCase


class TestBookmarkModel(BloomerpModelTestCase):
    model = Bookmark
