# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user_list_view_preference import UserListViewPreference
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserListViewPreferenceModel(BloomerpModelTestCase):
    model = UserListViewPreference
