# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user import User
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserModel(BloomerpModelTestCase):
    model = User
