# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user_detail_view_tabs_preference import UserDetailViewTabsPreference
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserDetailViewTabsPreferenceModel(BloomerpModelTestCase):
    model = UserDetailViewTabsPreference
