# Generated by manage.py generate_test_cases.
from bloomerp.models.users.user_detail_view_tabs_preference import UserDetailViewTabItem
from bloomerp.tests.base import BloomerpModelTestCase


class TestUserDetailViewTabItemModel(BloomerpModelTestCase):
    model = UserDetailViewTabItem
