# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestExecuteInboxActionComponent(BloomerpComponentTestCase):
    """Tests function `execute_inbox_action` from `bloomerp/components/communication/execute_inbox_action.py`."""

    view_name = 'components_execute_inbox_action'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
