# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenderInboxFolderComponent(BloomerpComponentTestCase):
    """Tests function `render_inbox_folder` from `bloomerp/components/communication/render_inbox_folder_items.py`."""

    view_name = 'components_render_inbox_folder_items'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
