# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestSelectInboxFolderComponent(BloomerpComponentTestCase):
    view_name = 'components_select_inbox_folder'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
