# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestCreateInboxComponent(BloomerpComponentTestCase):
    view_name = 'components_create_inbox'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
