# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDeleteInboxItemComponent(BloomerpComponentTestCase):
    """Tests function `delete_inbox_item` from `bloomerp/components/communication/delete_inbox_item.py`."""

    view_name = 'components_delete_inbox_item'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
