# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateInboxComponent(BloomerpComponentTestCase):
    """Tests function `create_inbox` from `bloomerp/components/communication/create_inbox.py`."""

    view_name = 'components_create_inbox'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
