# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestExecuteInboxActionComponent(BloomerpComponentTestCase):
    view_name = 'components_execute_inbox_action'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
