# Generated by manage.py generate_test_cases.
from bloomerp.automation.triggers.object_crud_trigger import ObjectCrudTrigger
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestOnObjectCreateOrUpdateNode(BloomerpWorkflowNodeTestCase):
    node_id = 'ON_OBJECT_CREATE_OR_UPDATE'
    executor_class = ObjectCrudTrigger

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
