# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.delete_object import DeleteObjectExecutor
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)
from django.contrib.contenttypes.models import ContentType


class TestDeleteObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'DELETE_OBJECT'
    executor_class = DeleteObjectExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        todo = Todo.objects.create(title="Delete this task")
        content_type = ContentType.objects.get_for_model(Todo)

        return [
            WorkflowNodeSimulation(
                name="Node deletes an object",
                parameters={
                    "content_type_id": content_type.id,
                    "object_id": todo.id,
                },
                output_validators=lambda output:(
                    output.get("status") == "success"
                    and
                    output.get("deleted_object_id") == str(todo.id)
                    and
                    Todo.objects.filter(pk=todo.id).exists() == False
                ),
            ),
            WorkflowNodeSimulation(
                name="Node deletes an object",
                parameters={
                    "content_type_id": content_type.id,
                    "object_id": "Wrong object ID",
                },
                output_validators=lambda output:(
                    output.get("status") == "error"
                ),
            ),
        ]
