# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.if_condition import IfConditionExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestIfConditionNode(BloomerpWorkflowNodeTestCase):
    node_id = 'IF_CONDITION'
    executor_class = IfConditionExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
