# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.send_email import SendEmailExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestSendEmailNode(BloomerpWorkflowNodeTestCase):
    node_id = 'SEND_EMAIL'
    executor_class = SendEmailExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
