# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.filter_objects import FilterObjectsExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestFilterObjectsNode(BloomerpWorkflowNodeTestCase):
    node_id = 'FILTER_OBJECTS'
    executor_class = FilterObjectsExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
