# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.delete_object import DeleteObjectExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestDeleteObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'DELETE_OBJECT'
    executor_class = DeleteObjectExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
