# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.update_object import UpdateObjectExecutor
from bloomerp.models.application_field import ApplicationField
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)
from django.contrib.contenttypes.models import ContentType


class TestUpdateObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'UPDATE_OBJECT'
    executor_class = UpdateObjectExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        todo = Todo.objects.create(title="Prepare report")
        content_type = ContentType.objects.get_for_model(Todo)

        return [
            WorkflowNodeSimulation(
                name="Node updates an object with resolved fields",
                parameters={
                    "content_type_id": content_type.id,
                    "object_id": todo.id,
                    "data": {"title": "{{ input.title }}"},
                },
                trigger_data={"title": "Submit report"},
                output_validators=lambda output: output.get("status") == "success",
            ),
        ]

