# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.human_in_the_loop import HumanInTheLoopExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestHumanInTheLoopNode(BloomerpWorkflowNodeTestCase):
    node_id = 'HUMAN_IN_THE_LOOP'
    executor_class = HumanInTheLoopExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
