# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.for_each import ForEachExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestForEachNode(BloomerpWorkflowNodeTestCase):
    node_id = 'FOR_EACH'
    executor_class = ForEachExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
