# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.generate_pdf import GeneratePdfExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestGeneratePdfNode(BloomerpWorkflowNodeTestCase):
    node_id = 'GENERATE_PDF'
    executor_class = GeneratePdfExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return [
            WorkflowNodeSimulation(
                name=""
            )
        ]
