# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.compute import ComputeExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestComputeNode(BloomerpWorkflowNodeTestCase):
    node_id = 'COMPUTE'
    executor_class = ComputeExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
