# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.object_if_condition import ObjectIfConditionExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestObjectIfConditionNode(BloomerpWorkflowNodeTestCase):
    node_id = 'OBJECT_IF_CONDITION'
    executor_class = ObjectIfConditionExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
