# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.list_objects import ListObjectsExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestListObjectsNode(BloomerpWorkflowNodeTestCase):
    node_id = 'LIST_OBJECTS'
    executor_class = ListObjectsExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
