# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.enrich import EnrichExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestEnrichDataNode(BloomerpWorkflowNodeTestCase):
    node_id = 'ENRICH_DATA'
    executor_class = EnrichExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
