# Generated by manage.py generate_test_cases.
from bloomerp.automation.triggers.object_crud_trigger import ObjectCrudTrigger
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestOnObjectDeleteNode(BloomerpWorkflowNodeTestCase):
    node_id = 'ON_OBJECT_DELETE'
    executor_class = ObjectCrudTrigger

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
