# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.update_object import UpdateObjectExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestUpdateObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'UPDATE_OBJECT'
    executor_class = UpdateObjectExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
