# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.wait import WaitExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestWaitNode(BloomerpWorkflowNodeTestCase):
    node_id = 'WAIT'
    executor_class = WaitExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
