# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.list_objects import ListObjectsExecutor
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)
from django.contrib.contenttypes.models import ContentType


class TestListObjectsNode(BloomerpWorkflowNodeTestCase):
    node_id = 'LIST_OBJECTS'
    executor_class = ListObjectsExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        Todo.objects.create(title="First task")
        Todo.objects.create(title="Second task")
        content_type = ContentType.objects.get_for_model(Todo)

        return [
            WorkflowNodeSimulation(
                name="Node lists objects for its content type",
                parameters={"content_type_id": content_type.id},
                output_validators=lambda output: (
                    output.get("count") == 2
                    and output.get("content_type_id") == content_type.id
                    and [item["title"] for item in output.get("queryset", [])]
                    == ["First task", "Second task"]
                ),
            ),
        ]
