# Generated by manage.py generate_test_cases.
from bloomerp.automation.flows.collect import CollectExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestCollectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'COLLECT'
    executor_class = CollectExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
