# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.sql_query import SqlQueryActionExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestSqlQueryNode(BloomerpWorkflowNodeTestCase):
    node_id = 'SQL_QUERY'
    executor_class = SqlQueryActionExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
