# Generated by manage.py generate_test_cases.
from bloomerp.automation.triggers.on_schedule_trigger import ScheduleTrigger
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestScheduleNode(BloomerpWorkflowNodeTestCase):
    node_id = 'SCHEDULE'
    executor_class = ScheduleTrigger

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
