# Generated by manage.py generate_test_cases.
from bloomerp.automation.triggers.human_trigger import HumanTrigger
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestHumanTriggerNode(BloomerpWorkflowNodeTestCase):
    node_id = 'HUMAN_TRIGGER'
    executor_class = HumanTrigger

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
