# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.merge_branches import MergeBranchExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestMergeBranchesNode(BloomerpWorkflowNodeTestCase):
    node_id = 'MERGE_BRANCHES'
    executor_class = MergeBranchExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
