# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.extract_field import ExtractFieldExecutor
from bloomerp.automation.schema import (
    WorkflowIOSchema,
    WorkflowValueField,
    WorkflowValueType,
)
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestExtractFieldNode(BloomerpWorkflowNodeTestCase):
    node_id = 'EXTRACT_FIELD'
    executor_class = ExtractFieldExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return [
            WorkflowNodeSimulation(
                name="Node extracts an object field",
                parameters={"field_path": "user"},
                trigger_data={"user": {"email": "john.doe@example.com"}},
                expected_output={"email": "john.doe@example.com"},
            ),
            WorkflowNodeSimulation(
                name="Node extracts a primitive field",
                parameters={"field_path": "user"},
                trigger_data={"user": "David"},
                expected_output="David",
            ),
            WorkflowNodeSimulation(
                name="Node extracts a nested field",
                parameters={"field_path": "user.profile.email"},
                trigger_data={"user": {"profile": {"email": "john.doe@example.com"}}},
                expected_output="john.doe@example.com",
            ),
            WorkflowNodeSimulation(
                name="Node extracts a list",
                parameters={"field_path": "interests"},
                trigger_data={"interests": ["sports", "music"]},
                expected_output=["sports", "music"],
                input_schema=WorkflowIOSchema(
                    value_type=WorkflowValueType.OBJECT,
                    fields=[
                        WorkflowValueField(
                            path="interests",
                            label="Interests",
                            value_type=WorkflowValueType.LIST,
                        ),
                    ],
                ),
                output_schema_validators=lambda schema: (
                    schema.value_type == WorkflowValueType.LIST
                    and schema.fields == []
                ),
            ),
        ]
