# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.get_object import GetObjectExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestGetObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'GET_OBJECT'
    executor_class = GetObjectExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
