# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.create_object import CreateObjectExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestCreateObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'CREATE_OBJECT'
    executor_class = CreateObjectExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
