# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.send_user_message import SendUserMessage
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)


class TestSendUserMessageNode(BloomerpWorkflowNodeTestCase):
    node_id = 'SEND_USER_MESSAGE'
    executor_class = SendUserMessage

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        return []
