# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.get_object import GetObjectExecutor
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)
from django.contrib.contenttypes.models import ContentType

class TestGetObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'GET_OBJECT'
    executor_class = GetObjectExecutor

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        TITLE = "123"

        todo_obj = Todo.objects.create(
            title=TITLE
        )
        ct = ContentType.objects.get_for_model(Todo)


        return [
            WorkflowNodeSimulation(
                name="Node retrieves object",
                parameters={
                    "content_type_id" : ct.id,
                    "object_id" : todo_obj.id
                },
                output_validators=[
                    lambda output: (
                        output.get("found") == True
                        and
                        output.get("instance").get("title") == TITLE
                    )
                ]
            ),
            WorkflowNodeSimulation(
                name="Node can't find object",
                parameters={
                    "content_type_id" : ct.id,
                    "object_id" : "INVALID"
                },
                output_validators=[
                    lambda output: (output.get("found") == False and output.get("instance") == None)
                ]
            ),
            WorkflowNodeSimulation(
                name="Node retrieves an object using a resolved ID",
                parameters={
                    "content_type_id": ct.id,
                    "object_id": "{{ input.instance_id }}",
                },
                trigger_data={"instance_id": str(todo_obj.id)},
                output_validators=lambda output: (
                    output.get("found") is True
                    and output.get("instance", {}).get("title") == TITLE
                ),
            ),
        ]
