# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.extract_field import ExtractFieldExecutor
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowSimulation,
)


class TestExtractFieldNode(BloomerpWorkflowNodeTestCase):
    node_id = 'EXTRACT_FIELD'
    executor_class = ExtractFieldExecutor

    def get_simulations(self) -> list[WorkflowSimulation]:
        return []
