# Generated by manage.py generate_test_cases.
from bloomerp.automation.actions.create_object import CreateObjectExecutor
from bloomerp.models.application_field import ApplicationField
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import (
    BloomerpWorkflowNodeTestCase,
    WorkflowNodeSimulation,
)
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType


class TestCreateObjectNode(BloomerpWorkflowNodeTestCase):
    node_id = 'CREATE_OBJECT'
    executor_class = CreateObjectExecutor

    def setUp(self) -> None:
        super().setUp()
        todo_content_type = ContentType.objects.get_for_model(Todo)
        user_content_type = ContentType.objects.get_for_model(get_user_model())
        for field, field_type, related_model in [
            ("title", "CharField", None),
            ("requested_by", "UserField", user_content_type),
        ]:
            ApplicationField.objects.get_or_create(
                content_type=todo_content_type,
                field=field,
                defaults={
                    "field_type": field_type,
                    "related_model": related_model,
                    "db_table": Todo._meta.db_table,
                    "db_column": field,
                    "db_field_type": field_type,
                },
            )

    def get_simulations(self) -> list[WorkflowNodeSimulation]:
        todo_content_type = ContentType.objects.get_for_model(Todo)
        user = get_user_model().objects.create_user(
            username="creator",
            password="testpassword",
        )

        return [
            WorkflowNodeSimulation(
                name="Node creates an object with configured fields",
                parameters={
                    "content_type_id": todo_content_type.id,
                    "data": {"title": "Prepare report"},
                },
                output_validators=lambda output: (
                    output.get("status") == "success"
                    and Todo.objects.filter(title="Prepare report").exists()
                ),
            ),
            WorkflowNodeSimulation(
                name="Node creates an object with resolved fields",
                parameters={
                    "content_type_id": todo_content_type.id,
                    "data": {"title": "{{ input.title }}"},
                },
                trigger_data={"title": "Submit report"},
                output_validators=lambda output: (
                    output.get("status") == "success"
                    and Todo.objects.filter(title="Submit report").exists()
                ),
            ),
            WorkflowNodeSimulation(
                name="Node creates an object with a user relationship",
                parameters={
                    "content_type_id": todo_content_type.id,
                    "data": {
                        "title": "Review report",
                        "requested_by": user.id,
                    },
                },
                output_validators=lambda output: (
                    output.get("status") == "success"
                    and Todo.objects.filter(
                        title="Review report",
                        requested_by=user,
                    ).exists()
                ),
            ),
        ]
