# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestMoveFileBrowserItemComponent(BloomerpComponentTestCase):
    view_name = 'components_files_move_browser_item'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
