# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestDeleteFileComponent(BloomerpComponentTestCase):
    view_name = 'components_files_delete'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
