# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestRenameFolderComponent(BloomerpComponentTestCase):
    view_name = 'components_files_rename_folder'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
