# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateFolderComponent(BloomerpComponentTestCase):
    """Tests function `create_folder` from `bloomerp/components/files/create_folder.py`."""

    view_name = 'components_create_folder'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
