# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenameFileComponent(BloomerpComponentTestCase):
    """Tests function `rename_file` from `bloomerp/components/files/rename_file_browser_item.py`."""

    view_name = 'components_files_rename'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
