# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDeleteFolderComponent(BloomerpComponentTestCase):
    """Tests function `delete_folder` from `bloomerp/components/files/delete_file_browser_item.py`."""

    view_name = 'components_files_delete_folder'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
