# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestAiConversationsComponent(BloomerpComponentTestCase):
    view_name = 'components_ai_conversations'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
