# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestAiConversationsComponent(BloomerpComponentTestCase):
    """Tests function `ai_conversations` from `bloomerp/components/llm/ai_conversations.py`."""

    view_name = 'components_ai_conversations'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
