// Generated by `./scripts.sh update-field-types`. Do not edit directly.

export class FieldTypeDefinition {
    public readonly id: string;

    public constructor(id: string) {
        this.id = id;
    }
}

export class FieldType {
    public static readonly PROPERTY = new FieldTypeDefinition('Property');
    public static readonly AUTO_FIELD = new FieldTypeDefinition('AutoField');
    public static readonly BIG_AUTO_FIELD = new FieldTypeDefinition('BigAutoField');
    public static readonly SMALL_AUTO_FIELD = new FieldTypeDefinition('SmallAutoField');
    public static readonly CHAR_FIELD = new FieldTypeDefinition('CharField');
    public static readonly CODE_FIELD = new FieldTypeDefinition('CodeField');
    public static readonly CHOICE_FIELD = new FieldTypeDefinition('ChoiceField');
    public static readonly TEXT_FIELD = new FieldTypeDefinition('TextField');
    public static readonly EMAIL_FIELD = new FieldTypeDefinition('EmailField');
    public static readonly URL_FIELD = new FieldTypeDefinition('URLField');
    public static readonly ADDRESS_FIELD = new FieldTypeDefinition('AddressField');
    public static readonly PHONE_NUMBER_FIELD = new FieldTypeDefinition('PhoneNumberField');
    public static readonly SLUG_FIELD = new FieldTypeDefinition('SlugField');
    public static readonly INTEGER_FIELD = new FieldTypeDefinition('IntegerField');
    public static readonly FLOAT_FIELD = new FieldTypeDefinition('FloatField');
    public static readonly DECIMAL_FIELD = new FieldTypeDefinition('DecimalField');
    public static readonly POSITIVE_INTEGER_FIELD = new FieldTypeDefinition('PositiveIntegerField');
    public static readonly POSITIVE_SMALL_INTEGER_FIELD = new FieldTypeDefinition('PositiveSmallIntegerField');
    public static readonly BIG_INTEGER_FIELD = new FieldTypeDefinition('BigIntegerField');
    public static readonly SMALL_INTEGER_FIELD = new FieldTypeDefinition('SmallIntegerField');
    public static readonly BOOLEAN_FIELD = new FieldTypeDefinition('BooleanField');
    public static readonly NULL_BOOLEAN_FIELD = new FieldTypeDefinition('NullBooleanField');
    public static readonly DATE_FIELD = new FieldTypeDefinition('DateField');
    public static readonly WEEK_FIELD = new FieldTypeDefinition('WeekField');
    public static readonly DATE_TIME_FIELD = new FieldTypeDefinition('DateTimeField');
    public static readonly TIME_FIELD = new FieldTypeDefinition('TimeField');
    public static readonly DURATION_FIELD = new FieldTypeDefinition('DurationField');
    public static readonly FILE_FIELD = new FieldTypeDefinition('FileField');
    public static readonly IMAGE_FIELD = new FieldTypeDefinition('ImageField');
    public static readonly FOREIGN_KEY = new FieldTypeDefinition('ForeignKey');
    public static readonly ONE_TO_ONE_FIELD = new FieldTypeDefinition('OneToOneField');
    public static readonly MANY_TO_MANY_FIELD = new FieldTypeDefinition('ManyToManyField');
    public static readonly ONE_TO_MANY_FIELD = new FieldTypeDefinition('OneToManyField');
    public static readonly USER_FIELD = new FieldTypeDefinition('UserField');
    public static readonly ONE_TO_ONE_USER_FIELD = new FieldTypeDefinition('OneToOneUserField');
    public static readonly UUID_FIELD = new FieldTypeDefinition('UUIDField');
    public static readonly BINARY_FIELD = new FieldTypeDefinition('BinaryField');
    public static readonly IP_ADDRESS_FIELD = new FieldTypeDefinition('IPAddressField');
    public static readonly GENERIC_IP_ADDRESS_FIELD = new FieldTypeDefinition('GenericIPAddressField');
    public static readonly JSON_FIELD = new FieldTypeDefinition('JSONField');
    public static readonly ARRAY_FIELD = new FieldTypeDefinition('ArrayField');
    public static readonly HSTORE_FIELD = new FieldTypeDefinition('HStoreField');
    public static readonly GENERIC_RELATION = new FieldTypeDefinition('GenericRelation');
    public static readonly GENERIC_FOREIGN_KEY = new FieldTypeDefinition('GenericForeignKey');
    public static readonly STATUS_FIELD = new FieldTypeDefinition('StatusField');
    public static readonly ICON_FIELD = new FieldTypeDefinition('IconField');
    public static readonly BLOOMERP_FILE_FIELD = new FieldTypeDefinition('BloomerpFileField');
    public static readonly FILES_RELATION_FIELD = new FieldTypeDefinition('FilesRelationField');
}
