# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.tile import Tile
from bloomerp.tests.base import (
    BloomerpAPIDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestSaveCanvasStateView(BloomerpAPIDetailViewTestCase):
    """Tests function `save_canvas_state` from `bloomerp/views/api/workspaces/tile.py`."""

    view_name = 'api_tile_canvas_state'
    model = Tile

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
