# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpListApiView(BloomerpAPIModelViewTestCase):
    """Tests class `BloomerpListApiView` from `bloomerp/views/api/generic/list.py`."""

    view_name = 'cost_centers-list'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
