# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpDetailApiView(BloomerpAPIDetailViewTestCase):
    """Tests class `BloomerpDetailApiView` from `bloomerp/views/api/generic/detail.py`."""

    view_name = 'cost_centers-detail'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
