# Generated by manage.py generate_test_cases.
from bloomerp.models.api.api_key import ApiKey
from bloomerp.tests.base import BloomerpModelViewTestCase


class TestCreateApiTokenView(BloomerpModelViewTestCase):
    view_name = 'add'
    model = ApiKey

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
