# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.policy import Policy
from bloomerp.tests.base import (
    BloomerpAPIDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestPolicyDetailApiView(BloomerpAPIDetailViewTestCase):
    """Tests class `PolicyDetailApiView` from `bloomerp/views/api/access_control/policy.py`."""

    view_name = 'access_control_policies-detail'
    model = Policy

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
