# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template_header import DocumentTemplateHeader
from bloomerp.tests.base import BloomerpModelTestCase


class TestDocumentTemplateHeaderModel(BloomerpModelTestCase):
    model = DocumentTemplateHeader
