# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template_styling import DocumentTemplateStyling
from bloomerp.tests.base import BloomerpModelTestCase


class TestDocumentTemplateStylingModel(BloomerpModelTestCase):
    model = DocumentTemplateStyling
