# Generated by manage.py generate_test_cases.
from bloomerp.models.document_templates.document_template import DocumentTemplate
from bloomerp.tests.base import BloomerpModelTestCase


class TestDocumentTemplateModel(BloomerpModelTestCase):
    model = DocumentTemplate
