# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpModuleViewTestCase


class TestDownloadSdkviewView(BloomerpModuleViewTestCase):
    view_name = 'download_sdk'
    module = 'misc'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
