# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModuleViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModuleRequestSetup,
)


class TestDownloadSdkviewView(BloomerpModuleViewTestCase):
    """Tests class `DownloadSDKView` from `bloomerp/views/sdk/dowload_sdk.py`."""

    view_name = 'download_sdk'
    module = 'misc'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
