# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestGlobalSearchComponent(BloomerpComponentTestCase):
    """Tests function `global_search` from `bloomerp/components/search/global_search.py`."""

    view_name = 'components_global_search'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
