# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form_submission import FormSubmission
from bloomerp.tests.base import BloomerpModelTestCase


class TestFormSubmissionModel(BloomerpModelTestCase):
    model = FormSubmission
