# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.tests.base import BloomerpModelTestCase


class TestFormModel(BloomerpModelTestCase):
    model = Form
