# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import BloomerpModelViewTestCase


class TestCreateEmailAccountView(BloomerpModelViewTestCase):
    view_name = 'add'
    model = EmailAccount

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
