# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestCreateEmailAccountView(BloomerpModelViewTestCase):
    """Tests class `CreateEmailAccountView` from `bloomerp/views/communication/create_email_account.py`."""

    view_name = 'add'
    model = EmailAccount

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
