# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpBulkUploadView(BloomerpModelViewTestCase):
    """Tests class `BloomerpBulkUploadView` from `bloomerp/views/generic/model/bulk_upload.py`."""

    view_name = 'bulk_upload'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
