# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBloomerpListView(BloomerpModelViewTestCase):
    """Tests class `BloomerpListView` from `bloomerp/views/generic/model/list.py`."""

    view_name = 'model'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
