# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpViewTestCase


class TestBloomerpFileListView(BloomerpViewTestCase):
    view_name = 'app'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
