# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpModelViewTestCase


class TestBloomerpBulkUploadView(BloomerpModelViewTestCase):
    view_name = 'bulk_upload'
    model = None

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
