# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBloomerpFileListView(BloomerpViewTestCase):
    """Tests class `BloomerpFileListView` from `bloomerp/views/generic/model/file_list.py`."""

    view_name = 'app'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
