# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestManageAccessControlForModelViewManagePermissionsClassView(BloomerpModelViewTestCase):
    """Tests class `ManageAccessControlForModelView` from `bloomerp/views/access_control/manage_permissions.py`."""

    view_name = 'Create Policy for {model}'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
