# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestManageAccessControlForModelViewPolicyListClassView(BloomerpModelViewTestCase):
    """Tests class `ManageAccessControlForModelView` from `bloomerp/views/access_control/policy_list.py`."""

    view_name = 'cost_centers_manageaccesscontrolformodelview'
    model = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
