# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.policy import Policy
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestUpdatePolicyView(BloomerpDetailViewTestCase):
    """Tests class `UpdatePolicyView` from `bloomerp/views/access_control/update.py`."""

    view_name = 'Update'
    model = Policy

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
