# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.policy import Policy
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestUpdatePolicyView(BloomerpDetailViewTestCase):
    view_name = 'Update'
    model = Policy

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
