# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.email_account import EmailAccount
from bloomerp.tests.base import BloomerpModelTestCase


class TestEmailAccountModel(BloomerpModelTestCase):
    model = EmailAccount
