# Generated by manage.py generate_test_cases.
from bloomerp.models.communication.comment import Comment
from bloomerp.tests.base import BloomerpModelTestCase


class TestCommentModel(BloomerpModelTestCase):
    model = Comment
