# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.field_policy import FieldPolicy
from bloomerp.tests.base import BloomerpModelTestCase


class TestFieldPolicyModel(BloomerpModelTestCase):
    model = FieldPolicy
