# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.row_policy_rule import RowPolicyRule
from bloomerp.tests.base import BloomerpModelTestCase


class TestRowPolicyRuleModel(BloomerpModelTestCase):
    model = RowPolicyRule
