# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.policy import Policy
from bloomerp.tests.base import BloomerpModelTestCase


class TestPolicyModel(BloomerpModelTestCase):
    model = Policy
