# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.row_policy_rule import RowPolicyRulePermission
from bloomerp.tests.base import BloomerpModelTestCase


class TestRowPolicyRulePermissionModel(BloomerpModelTestCase):
    model = RowPolicyRulePermission
