# Generated by manage.py generate_test_cases.
from bloomerp.models.access_control.row_policy import RowPolicy
from bloomerp.tests.base import BloomerpModelTestCase


class TestRowPolicyModel(BloomerpModelTestCase):
    model = RowPolicy
