# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestBulkUploadFormComponent(BloomerpComponentTestCase):
    view_name = 'components_bulk_upload_form'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
