# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBulkUploadFormComponent(BloomerpComponentTestCase):
    """Tests function `bulk_upload_form` from `bloomerp/components/bulk_actions/bulk_upload.py`."""

    view_name = 'components_bulk_upload_form'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
