# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestFiltersInitComponent(BloomerpComponentTestCase):
    """Tests function `filters_init` from `bloomerp/components/filters/fields.py`."""

    view_name = 'components_filters_init'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
