# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestSubmitFormView(BloomerpDetailViewTestCase):
    view_name = 'submit'
    model = Form

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
