# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form_submission import FormSubmission
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestReviewFormSubmissionView(BloomerpDetailViewTestCase):
    view_name = 'Review Submission'
    model = FormSubmission

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
