# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestBuilderView(BloomerpDetailViewTestCase):
    view_name = 'form_builder'
    model = Form

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
