# Generated by Django 5.1.1 on 2026-07-09 13:09

import bloomerp.model_fields.one_to_one_user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0005_employee_initiation_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='initiation_week',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=bloomerp.model_fields.one_to_one_user_field.OneToOneUserField(blank=True, help_text='Associated user account for login', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
