# Generated by Django 5.1.1 on 2026-08-03 16:49

import bloomerp.model_fields.week_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0006_remove_employee_initiation_week_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_week',
            field=bloomerp.model_fields.week_field.WeekField(blank=True, help_text='The week the employee started', max_length=8, null=True, verbose_name='Start week'),
        ),
    ]
