import bloomerp.model_fields.user_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0007_employee_active_employee_start_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True, help_text='Whether users can post directly to this account', verbose_name='Allow Manual Posting'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency used by this account', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening balance for the current fiscal year', max_digits=15, verbose_name='Opening Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='requires_reconciliation',
            field=models.BooleanField(default=False, help_text='Whether activity on this account should be reconciled', verbose_name='Requires Reconciliation'),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Default tax code for transactions posted to the account', max_length=20, null=True, verbose_name='Default Tax Code'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='net_change',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Net Change'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='year_to_date_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Year To Date Balance'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='year_to_date_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Year To Date Credit'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='year_to_date_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Year To Date Debit'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_primary',
            field=models.BooleanField(default=False, help_text=None, verbose_name='Primary Account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_reconciled_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Last Reconciled Balance'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_reconciled_date',
            field=models.DateField(blank=True, help_text=None, null=True, verbose_name='Last Reconciled Date'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance at the start of the current fiscal year', max_digits=15, verbose_name='Opening Balance'),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_version',
            field=models.CharField(default='BASE', help_text=None, max_length=20, verbose_name='Budget Version'),
        ),
        migrations.AddField(
            model_name='budget',
            name='committed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Committed Amount'),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_center',
            field=models.CharField(blank=True, help_text=None, max_length=20, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='forecast_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Forecast Amount'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='is_year_end',
            field=models.BooleanField(default=False, help_text=None, verbose_name='Year End Period'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='notes',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='quarter',
            field=models.IntegerField(default=1, help_text='Calendar quarter containing the period', verbose_name='Quarter'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='batch_number',
            field=models.CharField(blank=True, help_text=None, max_length=30, null=True, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text=None, max_digits=15, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text=None, verbose_name='Reconciled'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='line_number',
            field=models.IntegerField(default=1, help_text=None, verbose_name='Line Number'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='reconciliation_date',
            field=models.DateField(blank=True, help_text=None, null=True, verbose_name='Reconciliation Date'),
        ),
        migrations.AddField(
            model_name='gltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('REVALUATION', 'Revaluation')], default='DEBIT', help_text=None, max_length=50, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='journal',
            name='default_currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sequence_prefix',
            field=models.CharField(blank=True, help_text='Prefix used when numbering entries in this journal', max_length=10, null=True, verbose_name='Sequence Prefix'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='document_date',
            field=models.DateField(blank=True, help_text='Date shown on the source document', null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='due_date',
            field=models.DateField(blank=True, help_text=None, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Rate from the transaction currency to the ledger currency', max_digits=15, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text=None, verbose_name='Recurring Entry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='recurrence_key',
            field=models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Recurrence Key'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_system',
            field=models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Source System'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='due_date',
            field=models.DateField(blank=True, help_text=None, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text=None, max_digits=15, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text=None, max_digits=15, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text=None, max_digits=7, verbose_name='Tax Rate'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account associated to this account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Parent account for hierarchical structure', null=True, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.account', verbose_name='Parent Account'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(help_text=None, max_length=20, unique=True, verbose_name='Customer Code')),
                ('customer_name', models.CharField(help_text=None, max_length=200, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, help_text=None, max_length=254, null=True, verbose_name='Billing Email')),
                ('phone', models.CharField(blank=True, help_text=None, max_length=30, null=True, verbose_name='Billing Phone')),
                ('billing_address', models.TextField(blank=True, help_text=None, null=True, verbose_name='Billing Address')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('payment_terms_days', models.IntegerField(default=30, help_text=None, verbose_name='Payment Terms Days')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Credit Limit')),
                ('tax_number', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Tax Number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('INACTIVE', 'Inactive')], help_text=None, max_length=50, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text=None, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('crm_account', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.crmaccount', verbose_name='CRM Account')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'finance_accounts_receivable_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text=None, max_length=30, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(help_text=None, verbose_name='Invoice Date')),
                ('due_date', models.DateField(help_text=None, verbose_name='Due Date')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text=None, max_digits=15, verbose_name='Exchange Rate')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Paid Amount')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Outstanding Amount')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], help_text=None, max_length=50, verbose_name='Status')),
                ('sales_order_number', models.CharField(blank=True, help_text=None, max_length=30, null=True, verbose_name='Sales Order Number')),
                ('customer_reference', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Customer Reference')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.customer', verbose_name='Customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.journalentry', verbose_name='Journal Entry')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Invoice',
                'verbose_name_plural': 'Customer Invoices',
                'db_table': 'finance_accounts_receivable_customer_invoice',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLine',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.IntegerField(help_text=None, verbose_name='Line Number')),
                ('product_code', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Product Code')),
                ('description', models.TextField(help_text=None, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text=None, max_digits=15, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text=None, max_digits=7, verbose_name='Tax Rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Line Total')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.CASCADE, to='bloomerp_modules.customerinvoice', verbose_name='Invoice')),
                ('revenue_account', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.account', verbose_name='Revenue Account')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Invoice Line',
                'verbose_name_plural': 'Customer Invoice Lines',
                'db_table': 'finance_accounts_receivable_customer_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text=None, max_length=30, unique=True, verbose_name='Receipt Number')),
                ('receipt_date', models.DateField(help_text=None, verbose_name='Receipt Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('ACH', 'ACH'), ('WIRE', 'Wire'), ('CARD', 'Card'), ('CHECK', 'Check')], help_text=None, max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], help_text=None, max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('bank_account', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.bankaccount', verbose_name='Bank Account')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.customer', verbose_name='Customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.journalentry', verbose_name='Journal Entry')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Receipt',
                'verbose_name_plural': 'Customer Receipts',
                'db_table': 'finance_accounts_receivable_customer_receipt',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(help_text=None, max_length=20, unique=True, verbose_name='Vendor Code')),
                ('vendor_name', models.CharField(help_text=None, max_length=200, verbose_name='Vendor Name')),
                ('email', models.EmailField(blank=True, help_text=None, max_length=254, null=True, verbose_name='Accounts Payable Email')),
                ('phone', models.CharField(blank=True, help_text=None, max_length=30, null=True, verbose_name='Vendor Phone')),
                ('address', models.TextField(blank=True, help_text=None, null=True, verbose_name='Vendor Address')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('payment_terms_days', models.IntegerField(default=30, help_text=None, verbose_name='Payment Terms Days')),
                ('tax_number', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Tax Number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('INACTIVE', 'Inactive')], help_text=None, max_length=50, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text=None, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('crm_account', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.crmaccount', verbose_name='CRM Account')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'finance_accounts_payable_vendor',
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text=None, max_length=30, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(help_text=None, verbose_name='Invoice Date')),
                ('due_date', models.DateField(help_text=None, verbose_name='Due Date')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text=None, max_digits=15, verbose_name='Exchange Rate')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Paid Amount')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Outstanding Amount')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], help_text=None, max_length=50, verbose_name='Status')),
                ('purchase_order_number', models.CharField(blank=True, help_text=None, max_length=30, null=True, verbose_name='Purchase Order Number')),
                ('vendor_reference', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Vendor Reference')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.journalentry', verbose_name='Journal Entry')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Invoice',
                'verbose_name_plural': 'Vendor Invoices',
                'db_table': 'finance_accounts_payable_vendor_invoice',
            },
        ),
        migrations.CreateModel(
            name='VendorInvoiceLine',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.IntegerField(help_text=None, verbose_name='Line Number')),
                ('item_code', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Item Code')),
                ('description', models.TextField(help_text=None, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text=None, max_digits=15, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text=None, max_digits=7, verbose_name='Tax Rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Line Total')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.account', verbose_name='Expense Account')),
                ('invoice', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.CASCADE, to='bloomerp_modules.vendorinvoice', verbose_name='Invoice')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Invoice Line',
                'verbose_name_plural': 'Vendor Invoice Lines',
                'db_table': 'finance_accounts_payable_vendor_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(help_text=None, max_length=30, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(help_text=None, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text=None, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', help_text=None, max_length=10, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('ACH', 'ACH'), ('WIRE', 'Wire'), ('CARD', 'Card'), ('CHECK', 'Check')], help_text=None, max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text=None, max_length=50, null=True, verbose_name='Reference Number')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], help_text=None, max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text=None, null=True, verbose_name='Notes')),
                ('bank_account', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.bankaccount', verbose_name='Bank Account')),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp_modules.journalentry', verbose_name='Journal Entry')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.PROTECT, to='bloomerp_modules.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
                'db_table': 'finance_accounts_payable_vendor_payment',
            },
        ),
    ]
