# Generated by Django 5.1.1 on 2026-08-24 14:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0009_alter_account_avatar_alter_account_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text=None, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
