# Generated by Django 5.1.1 on 2026-08-20 08:57

import bloomerp.model_fields.address_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp_modules', '0009_alter_account_avatar_alter_account_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=bloomerp.model_fields.address_field.AddressField(blank=True, help_text=None, null=True, verbose_name='Address'),
        ),
    ]
