# Generated by manage.py generate_test_cases.
from bloomerp.models.project_management.initiative import Initiative
from bloomerp.tests.base import BloomerpModelTestCase


class TestInitiativeModel(BloomerpModelTestCase):
    model = Initiative
