# Generated by manage.py generate_test_cases.
from bloomerp.models.project_management.todo_label import TodoLabel
from bloomerp.tests.base import BloomerpModelTestCase


class TestTodoLabelModel(BloomerpModelTestCase):
    model = TodoLabel
