# Generated by manage.py generate_test_cases.
from bloomerp.models.project_management.todo import Todo
from bloomerp.tests.base import BloomerpModelTestCase


class TestTodoModel(BloomerpModelTestCase):
    model = Todo
