# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestUpdateObjectComponent(BloomerpComponentTestCase):
    """Tests function `update_object` from `bloomerp/components/objects/crud/create_update.py`."""

    view_name = 'components_update_object'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
