from typing import Optional

from django.db.models import QuerySet

from bloomerp.model_fields.icon_field import IconField
from bloomerp.models.base_bloomerp_model import BloomerpModel
from django.db import models
from django.utils.translation import gettext_lazy as _


def get_tile_type_choices():
    from bloomerp.workspaces.tiles import TileType

    return [(tile.name, tile.value.name) for tile in TileType]

class Tile(BloomerpModel):
    """
    A tile represents a visual item that can be placed on a workspace.

    A default tile is one that can be set on models or modules which allow you to create
    default workspaces.
    """
    class Meta(BloomerpModel.Meta):
        verbose_name = _("Tile")
        verbose_name_plural = _("Tiles")
        managed = True
        db_table = 'bloomerp_tile'

    name = models.CharField(
        max_length=255, 
        help_text=_("Name of the widget"),
        verbose_name=_("Name"),
        )
    description = models.TextField(
        blank=True,
        null=True,
        help_text=_("Description of the widget"),
        verbose_name=_("Description"),
        )
    type = models.CharField(
        help_text=_("The type of tile"),
        max_length=32,
        choices=get_tile_type_choices,
        verbose_name=_("Type"),
    )
    icon = IconField(
        default="fa fa-chart-simple",
        verbose_name=_("Icon"),
    )
    schema = models.JSONField(verbose_name=_("Schema"))

    auto_generated = models.BooleanField(
        default=False,
        verbose_name=_("Auto Generated"),
        editable=False,
    )


    def __str__(self):
        return self.name

    @staticmethod
    def get_default_tiles() -> QuerySet["Tile"]:
        """
        Returns the default tiles that are auto-generated by the system.
        """
        return Tile.objects.filter(
            auto_generated=True,
            schema__id__isnull=False
        )

    @staticmethod
    def get_tile_by_native_id(native_id: str) -> Optional["Tile"]:
        """Returns the tile by the native ID.
        The native ID is the tile that the user has set on the definition.
        """
        return Tile.get_default_tiles().filter(
            schema__id=native_id,
        ).first()

    @staticmethod
    def get_tiles_by_native_ids(ids: list[str]) -> dict[str, "Tile"]:
        """Returns a dictionary of native tiles id's and the tile database object.
        """
        normalized_ids = {
            str(native_id).strip()
            for native_id in ids
            if str(native_id).strip()
        }
        return {
            str(tile.schema["id"]): tile
            for tile in Tile.get_default_tiles().filter(
                schema__id__in=normalized_ids,
            )
        }
