# Generated by manage.py generate_test_cases.
from bloomerp.models.forms.form import Form
from bloomerp.tests.base import (
    BloomerpAPIDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestFormSubmitView(BloomerpAPIDetailViewTestCase):
    """Tests function `form_submit_view` from `bloomerp/views/api/forms/submit.py`."""

    view_name = 'api_form_submit'
    model = Form

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
