# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSharePreferenceComponent(BloomerpComponentTestCase):
    """Tests function `share_preference` from `bloomerp/components/preferences/share_preference.py`."""

    view_name = 'components_share_preference'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
