# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSelectPreferenceComponent(BloomerpComponentTestCase):
    """Tests function `select_preference` from `bloomerp/components/preferences/select_preference.py`."""

    view_name = 'components_select_preference'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
