# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDeletePreferenceComponent(BloomerpComponentTestCase):
    """Tests function `delete_preference` from `bloomerp/components/preferences/delete_preference.py`."""

    view_name = 'components_delete_preference'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
