# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenderLayoutItemComponent(BloomerpComponentTestCase):
    """Tests function `render_layout_item` from `bloomerp/components/layout/render_layout_item.py`."""

    view_name = 'components_render_layout_item'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
