# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestAvailableLayoutItemsComponent(BloomerpComponentTestCase):
    view_name = 'components_available_layout_items'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
