# Generated by Django 5.1.1 on 2025-01-12 18:54

import bloomerp.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0071_aiconversation_auto_named"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="content",
            field=bloomerp.models.fields.TextEditorField(blank=True, null=True),
        ),
    ]
