# Generated by Django 5.1.1 on 2025-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0072_alter_todo_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="args",
            field=models.JSONField(
                blank=True, help_text="Extra arguments for the conversation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aiconversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("sql", "SQL"),
                    ("document_template", "Document Template Generator"),
                    ("tiny_mce_content", "TinyMCE Content Generator"),
                    ("bloom_ai", "Bloom AI"),
                    ("code", "Code Generator"),
                    ("object_bloom_ai", "Object Bloom AI"),
                ],
                default="bloom_ai",
                max_length=20,
            ),
        ),
    ]
