# Generated by Django 5.1.1 on 2026-07-06 15:03

import bloomerp.model_fields.user_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0035_initiative_todo_initiative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file_view_preference',
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the inbox, typically associated with the owner.', max_length=255)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Users who have access to this inbox.', related_name='inbox_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox',
            },
        ),
        migrations.CreateModel(
            name='InboxFolder',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('all', 'All'), ('in_app_notifications', 'Notifications'), ('email', 'Emails')], max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='bloomerp.inbox')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox Folder',
                'verbose_name_plural': 'Inbox Folders',
                'db_table': 'bloomerp_inbox_folder',
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('notification', 'Notification'), ('email', 'Email')], max_length=50)),
                ('related_item_id', models.CharField(blank=True, help_text="Optional reference to the source item's ID, if applicable.", max_length=255, null=True)),
                ('actor', models.CharField(blank=True, help_text='The actor or entity associated with the inbox item.', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the inbox item has been read by the user.')),
                ('title', models.CharField(help_text='The title of the inbox item.', max_length=1000)),
                ('snippet', models.TextField(blank=True, help_text='A brief snippet or summary of the inbox item content.', null=True)),
                ('raw_meta_data', models.JSONField(blank=True, help_text='Optional JSON field to store additional metadata related to the inbox item.', null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(help_text='The folder to which this inbox item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='bloomerp.inboxfolder')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox Item',
                'verbose_name_plural': 'Inbox Items',
                'db_table': 'bloomerp_inbox_item',
            },
        ),
        migrations.CreateModel(
            name='UserInboxPreference',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('selected_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_selected_inbox_preference', to='bloomerp.inbox')),
                ('selected_inbox_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_selected_inbox_folder_preference', to='bloomerp.inboxfolder')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inbox Preference',
                'verbose_name_plural': 'User Inbox Preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('outlook', 'Outlook'), ('google', 'Google'), ('imap', 'IMAP / SMTP'), ('other', 'Other')], default='imap', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error')], default='draft', max_length=32)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True, help_text='Encrypted password or app password used for providers that support direct SMTP/IMAP authentication.')),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(blank=True, null=True)),
                ('imap_security', models.CharField(choices=[('ssl_tls', 'SSL/TLS'), ('starttls', 'STARTTLS'), ('none', 'None')], default='ssl_tls', max_length=32)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_security', models.CharField(choices=[('ssl_tls', 'SSL/TLS'), ('starttls', 'STARTTLS'), ('none', 'None')], default='starttls', max_length=32)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('oauth_client_secret', models.TextField(blank=True, help_text='Encrypted OAuth client secret.')),
                ('oauth_tenant_id', models.CharField(blank=True, help_text='Provider tenant, directory, or workspace identifier when applicable.', max_length=255)),
                ('oauth_scopes', models.TextField(blank=True, help_text='Space-separated OAuth scopes requested for this account.')),
                ('access_token', models.TextField(blank=True, help_text='Encrypted OAuth access token.')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token.')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings that do not have dedicated fields yet.')),
                ('last_validated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('validation_error', models.TextField(blank=True, editable=False)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'bloomerp_email_account',
                'indexes': [models.Index(fields=['provider', 'status'], name='email_acc_provider_status_idx'), models.Index(fields=['email_address'], name='email_acc_address_idx')],
            },
        ),
    ]
