# Generated by Django 5.1.1 on 2026-07-11 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0036_alter_applicationfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreateviewpreference',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group'),
        ),
        migrations.AddField(
            model_name='usercreateviewpreference',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercreateviewpreference',
            name='initial_default',
            field=models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account."),
        ),
        migrations.AddField(
            model_name='usercreateviewpreference',
            name='source_object',
            field=models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.usercreateviewpreference'),
        ),
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='initial_default',
            field=models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account."),
        ),
        migrations.AddField(
            model_name='userdetailviewpreference',
            name='source_object',
            field=models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.userdetailviewpreference'),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group'),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='initial_default',
            field=models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account."),
        ),
        migrations.AddField(
            model_name='userlistviewpreference',
            name='source_object',
            field=models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.userlistviewpreference'),
        ),
        migrations.AlterField(
            model_name='usercreateviewpreference',
            name='name',
            field=models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercreateviewpreference',
            name='selected',
            field=models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.'),
        ),
        migrations.AlterField(
            model_name='usercreateviewpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetailviewpreference',
            name='name',
            field=models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetailviewpreference',
            name='selected',
            field=models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.'),
        ),
        migrations.AlterField(
            model_name='userdetailviewpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='name',
            field=models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='selected',
            field=models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.'),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
