# Generated by Django 5.1.1 on 2026-07-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0037_usercreateviewpreference_groups_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercreateviewpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object__isnull', False)), fields=('user', 'source_object'), name='unique_create_view_preference_reference'),
        ),
        migrations.AddConstraint(
            model_name='userdetailviewpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object__isnull', False)), fields=('user', 'source_object'), name='unique_detail_view_preference_reference'),
        ),
        migrations.AddConstraint(
            model_name='userlistviewpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object__isnull', False)), fields=('user', 'source_object'), name='unique_list_view_preference_reference'),
        ),
    ]
