# Generated by Django 5.1.1 on 2026-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0038_inboxitem_datetime_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='folders',
            field=models.JSONField(blank=True, default=list, help_text='Cached list of folders/mailboxes for this account.'),
        ),
    ]
