# Generated by Django 5.1.1 on 2026-07-13 13:12

from django.db import migrations, models


def repair_duplicate_sidebar_selections(apps, schema_editor):
    """Keep the oldest selected sidebar for each user before constraining it."""
    Sidebar = apps.get_model("bloomerp", "Sidebar")
    selected = Sidebar.objects.filter(selected=True).order_by("user_id", "pk")
    seen_user_ids = set()
    duplicate_ids = []

    for sidebar in selected.iterator():
        if sidebar.user_id in seen_user_ids:
            duplicate_ids.append(sidebar.pk)
        else:
            seen_user_ids.add(sidebar.user_id)

    if duplicate_ids:
        Sidebar.objects.filter(pk__in=duplicate_ids).update(selected=False)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0039_sidebar_initial_default_sidebar_shared_with_groups_and_more'),
    ]

    operations = [
        migrations.RunPython(
            repair_duplicate_sidebar_selections,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='sidebar',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('user',), name='unique_selected_sidebar_preference'),
        ),
    ]
