# Generated by Django 5.1.1 on 2026-07-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0039_emailaccount_folders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccount',
            old_name='folders',
            new_name='mailboxes',
        ),
    ]
