# Generated by Django 5.1.1 on 2026-07-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def empty_module_ids_to_null(apps, schema_editor):
    Workspace = apps.get_model('bloomerp', 'Workspace')
    Workspace.objects.filter(module_id='').update(module_id=None)


def null_module_ids_to_empty(apps, schema_editor):
    Workspace = apps.get_model('bloomerp', 'Workspace')
    Workspace.objects.filter(module_id__isnull=True).update(module_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0040_enforce_sidebar_selection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspace',
            name='unique_default_workspace_per_user_module_context',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='is_default',
            new_name='selected',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='shared_with',
            new_name='shared_with_users',
        ),
        migrations.AddField(
            model_name='workspace',
            name='initial_default',
            field=models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account."),
        ),
        migrations.AddField(
            model_name='workspace',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='source_object',
            field=models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='module_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RunPython(
            empty_module_ids_to_null,
            null_module_ids_to_empty,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='selected',
            field=models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('module_id__isnull', False), ('selected', True)), fields=('user', 'module_id'), name='unique_selected_workspace_per_user_module'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('module_id__isnull', True), ('selected', True)), fields=('user',), name='unique_selected_general_workspace_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object__isnull', False)), fields=('user', 'source_object'), name='unique_workspace_preference_reference'),
        ),
    ]
