# Generated by Django 5.1.1 on 2026-07-14 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0041_migrate_workspace_preference'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectLayoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255)),
                ('selected', models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.')),
                ('initial_default', models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account.")),
                ('content_type', models.ForeignKey(help_text='The content type of the model for which this preference applies.', on_delete=django.db.models.deletion.CASCADE, related_name='user_object_layout_preferences', to='contenttypes.contenttype')),
                ('shared_with_groups', models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group')),
                ('shared_with_users', models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL)),
                ('source_object', models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.userobjectlayoutpreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Object Layout Preference',
                'verbose_name_plural': 'User Object Layout Preferences',
                'unique_together': {('user', 'content_type')},
            },
        ),
    ]
