# Generated by Django 5.1.1 on 2026-07-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0043_alter_userobjectlayoutpreference_content_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userobjectlayoutpreference',
            unique_together=set(),
        ),
    ]
