# Generated by Django 5.1.1 on 2026-07-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0040_rename_folders_emailaccount_mailboxes'),
        ('bloomerp', '0045_userdetailviewtabspreference_and_items'),
    ]

    operations = [
    ]
