# Generated by Django 5.1.1 on 2026-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0047_consolidate_email_message_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documenttemplateheader',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='documenttemplatestyling',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filefolder',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete')},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete')},
        ),
        migrations.AlterModelOptions(
            name='initiative',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sqlquery',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True, 'permissions': [('execute_sql_query', 'Can execute SQL queries')], 'verbose_name': 'SQL Query', 'verbose_name_plural': 'SQL Queries'},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete')},
        ),
        migrations.AlterModelOptions(
            name='usercreateviewpreference',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userdetailviewpreference',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_change', 'bulk_delete'), 'managed': True},
        ),
        migrations.AddField(
            model_name='workflowrunstep',
            name='output_file',
            field=models.FileField(blank=True, help_text='Serialized output produced by this workflow node execution.', null=True, upload_to='workflow_run_outputs/'),
        ),
        migrations.AddField(
            model_name='workflowrunstep',
            name='state',
            field=models.JSONField(blank=True, help_text='Serializable workflow execution state captured after this step.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowrunstep',
            name='status',
            field=models.CharField(choices=[('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', help_text='The status of this workflow run step.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlistviewpreference',
            name='view_type',
            field=models.CharField(choices=[('table', 'Table'), ('kanban', 'Kanban'), ('card', 'Card'), ('calendar', 'Calendar'), ('gant', 'Gantt'), ('pivot_table', 'Pivot')], default='table', max_length=50),
        ),
    ]
