# Generated by Django 5.1.1 on 2026-07-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0048_alter_apikey_options_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrunstep',
            name='node',
            field=models.ForeignKey(blank=True, help_text='Reference to node object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloomerp.workflownode'),
        ),
        migrations.AlterField(
            model_name='workflowrunstep',
            name='status',
            field=models.CharField(choices=[('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', help_text='The status of this workflow run step.', max_length=20),
        ),
    ]
