# Generated by Django 5.1.1 on 2026-07-23 08:37

import bloomerp.model_fields.user_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloomerp', '0050_delete_beta_inbox_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Optional name for this preference, for user reference', max_length=255)),
                ('selected', models.BooleanField(default=False, help_text='Indicates if this preference is currently selected for the user. Only one preference per user can be selected at a time.')),
                ('initial_default', models.BooleanField(default=False, help_text="Indicates if this preference is the initial default for the user. This is used to determine the user's default preference when they first create an account.")),
                ('shared_with_groups', models.ManyToManyField(blank=True, help_text='Groups with whom this preference is shared.', related_name='shared_%(class)s_preferences', to='auth.group')),
                ('shared_with_users', models.ManyToManyField(blank=True, help_text='Users with whom this preference is shared.', related_name='shared_%(class)s_preferences', to=settings.AUTH_USER_MODEL)),
                ('source_object', models.ForeignKey(blank=True, help_text='Reference to the original preference from which this preference was derived. This is used to track the origin of derived preferences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_%(class)s_preferences', to='bloomerp.inbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox',
            },
        ),
        migrations.CreateModel(
            name='InboxFolder',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('all', 'All'), ('in_app_notifications', 'Notifications'), ('email', 'Emails')], max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='bloomerp.inbox')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox Folder',
                'verbose_name_plural': 'Inbox Folders',
                'db_table': 'bloomerp_inbox_folder',
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('notification', 'Notification'), ('email', 'Email')], max_length=50)),
                ('related_item_id', models.CharField(blank=True, help_text="Optional reference to the source item's ID, if applicable.", max_length=1000, null=True)),
                ('actor', models.CharField(blank=True, help_text='The actor or entity associated with the inbox item.', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the inbox item has been read by the user.')),
                ('datetime_received', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when the inbox item was received by its source system.', null=True)),
                ('title', models.CharField(help_text='The title of the inbox item.', max_length=1000)),
                ('snippet', models.TextField(blank=True, help_text='A brief snippet or summary of the inbox item content.', null=True)),
                ('raw_meta_data', models.JSONField(blank=True, help_text='Optional JSON field to store additional metadata related to the inbox item.', null=True)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(help_text='The folder to which this inbox item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='bloomerp.inboxfolder')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox Item',
                'verbose_name_plural': 'Inbox Items',
                'db_table': 'bloomerp_inbox_item',
            },
        ),
        migrations.CreateModel(
            name='UserInboxPreference',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('selected_inbox_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_selected_inbox_folder_preference', to='bloomerp.inboxfolder')),
                ('updated_by', bloomerp.model_fields.user_field.UserField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inbox Preference',
                'verbose_name_plural': 'User Inbox Preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='inbox',
            constraint=models.UniqueConstraint(condition=models.Q(('selected', True)), fields=('user',), name='unique_selected_inbox_preference'),
        ),
        migrations.AddConstraint(
            model_name='inbox',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object__isnull', False)), fields=('user', 'source_object'), name='unique_inbox_preference_reference'),
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'email'), ('related_item_id__isnull', False)), fields=('folder', 'item_type', 'related_item_id'), name='uniq_email_item_identity'),
        ),
    ]
