# Generated by Django 5.1.1 on 2026-07-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0051_inbox_inboxfolder_inboxitem_userinboxpreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='shared_with_groups',
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='shared_with_users',
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='source_object',
        ),
        migrations.RemoveField(
            model_name='userdetailviewpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCreateViewPreference',
        ),
        migrations.DeleteModel(
            name='UserDetailViewPreference',
        ),
    ]
