# Generated by Django 5.1.1 on 2026-08-19 13:44

import bloomerp.model_fields.user_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0056_alter_tile_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=bloomerp.model_fields.user_field.UserField(blank=True, help_text='The user to whom the todo is assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='requested_by',
            field=bloomerp.model_fields.user_field.UserField(blank=True, help_text='The user who requested the todo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_todos', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
    ]
