# Generated by Django 5.1.1 on 2026-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0057_alter_todo_assigned_to_alter_todo_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('scoped', 'Scoped'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='backlog', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('scoped', 'Scoped'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('duplicate', 'Duplicate')], default='backlog', max_length=50, verbose_name='Status'),
        ),
    ]
