# Generated by Django 5.1.1 on 2026-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0059_alter_applicationfield_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Document Template', 'verbose_name_plural': 'Document Templates'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplateheader',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Document Template Header', 'verbose_name_plural': 'Document Template Headers'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplatestyling',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Document Template Styling', 'verbose_name_plural': 'Document Template Stylings'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='filefolder',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'File Folder', 'verbose_name_plural': 'File Folders'},
        ),
        migrations.AlterModelOptions(
            name='initiative',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Initiative', 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterModelOptions(
            name='sqlquery',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'permissions': [('execute_sql_query', 'Can execute SQL queries')], 'verbose_name': 'SQL Query', 'verbose_name_plural': 'SQL Queries'},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Tile', 'verbose_name_plural': 'Tiles'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import', 'bulk_add', 'bulk_change', 'bulk_delete'), 'managed': True, 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
