# Generated by Django 5.1.1 on 2026-09-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0060_add_bulk_add_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent initiative of this initiative', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_initiatives', to='bloomerp.initiative', verbose_name='Parent Initiative'),
        ),
    ]
