# Generated by Django 5.1.1 on 2026-09-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerp', '0061_initiative_parent'),
        ('bloomerp', '0064_userlistviewpreference_registry_choices'),
    ]

    operations = [
    ]
