# Generated by manage.py generate_test_cases.
from bloomerp.models.audit.activity_log import ActivityLog
from bloomerp.tests.base import BloomerpModelTestCase


class TestActivityLogModel(BloomerpModelTestCase):
    model = ActivityLog
