# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestFieldDisplayOptionsComponent(BloomerpComponentTestCase):
    """Tests function `field_display_options` from `bloomerp/components/objects/details/field_display_options.py`."""

    view_name = 'components_field_display_options'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
