# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCommentsComponent(BloomerpComponentTestCase):
    """Tests function `comments` from `bloomerp/components/objects/details/comments.py`."""

    view_name = 'components_comments'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
