# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSaveAvatarComponent(BloomerpComponentTestCase):
    """Tests function `save_avatar` from `bloomerp/components/objects/details/save_avatar.py`."""

    view_name = 'components_save_avatar'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
