# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestRelatedFieldsComponent(BloomerpComponentTestCase):
    view_name = 'components_filters_related_fields'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
