# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestValueInputComponent(BloomerpComponentTestCase):
    view_name = 'components_filters_value_input'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
