# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestValueInputComponent(BloomerpComponentTestCase):
    """Tests function `value_input` from `bloomerp/components/application_fields/filters.py`."""

    view_name = 'components_filters_value_input'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
