# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestAssistantMutationCatalogView(BloomerpAPIViewTestCase):
    """Tests class `AssistantMutationCatalogView` from `bloomerp/views/api/mutations.py`."""

    view_name = 'api_assistant_mutation_catalog'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
