# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBloomerpApiRootView(BloomerpAPIViewTestCase):
    """Tests class `BloomerpApiRootView` from `bloomerp/views/api/root.py`."""

    view_name = 'api_root'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
