# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestAssistantMutationView(BloomerpAPIViewTestCase):
    """Tests class `AssistantMutationView` from `bloomerp/views/api/mutations.py`."""

    view_name = 'api_assistant_mutations'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
