# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestDocumentTemplateBuilderCatalogComponent(BloomerpComponentTestCase):
    view_name = 'components_document_template_builder_catalog'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
