# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestGenerateDocumentTemplateComponent(BloomerpComponentTestCase):
    view_name = 'components_generate_document_template'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
