# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDocumentTemplateBuilderCatalogComponent(BloomerpComponentTestCase):
    """Tests function `document_template_builder_catalog` from `bloomerp/components/document_templates/template_builder_catalog.py`."""

    view_name = 'components_document_template_builder_catalog'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
