# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.tile import Tile
from bloomerp.tests.base import BloomerpModelTestCase


class TestTileModel(BloomerpModelTestCase):
    model = Tile
