# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.sidebar_item import SidebarItem
from bloomerp.tests.base import BloomerpModelTestCase


class TestSidebarItemModel(BloomerpModelTestCase):
    model = SidebarItem
