# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.workspace import Workspace
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkspaceModel(BloomerpModelTestCase):
    model = Workspace
