# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.sql_query import SqlQuery
from bloomerp.tests.base import BloomerpModelTestCase


class TestSqlQueryModel(BloomerpModelTestCase):
    model = SqlQuery
