# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.sidebar import Sidebar
from bloomerp.tests.base import BloomerpModelTestCase


class TestSidebarModel(BloomerpModelTestCase):
    model = Sidebar
