# Generated by manage.py generate_test_cases.
from bloomerp.models.application_field import ApplicationField
from bloomerp.tests.base import BloomerpModelTestCase


class TestApplicationFieldModel(BloomerpModelTestCase):
    model = ApplicationField
