# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestNewEmailComponent(BloomerpComponentTestCase):
    """Tests function `new_email` from `bloomerp/components/communication/emails/new_email.py`."""

    view_name = 'components_new_email'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
