# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestNewEmailComponent(BloomerpComponentTestCase):
    view_name = 'components_new_email'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
