# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestSyncEmailsComponent(BloomerpComponentTestCase):
    view_name = 'components_sync_emails'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
