# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSyncEmailsComponent(BloomerpComponentTestCase):
    """Tests function `sync_emails` from `bloomerp/components/communication/emails/sync_emails.py`."""

    view_name = 'components_sync_emails'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
