# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestCreateTodoForObjectComponent(BloomerpComponentTestCase):
    view_name = 'components_create_todo_for_object'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
