# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateTodoForObjectComponent(BloomerpComponentTestCase):
    """Tests function `create_todo_for_object` from `bloomerp/components/todos/create_todo_for_object.py`."""

    view_name = 'components_create_todo_for_object'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
