import json
from pathlib import Path

from django.core.management.base import BaseCommand

from bloomerp.field_types.registry import load_builtin_field_types


class Command(BaseCommand):
    help = "Export registered field type IDs and symbolic names to TypeScript."

    def add_arguments(self, parser):
        parser.add_argument("output", type=Path)

    def handle(self, *args, **options):
        registry = load_builtin_field_types()
        lines = [
            "// Generated by `./scripts.sh update-field-types`. Do not edit directly.",
            "",
            "export class FieldTypeDefinition {",
            "    public readonly id: string;",
            "",
            "    public constructor(id: string) {",
            "        this.id = id;",
            "    }",
            "}",
            "",
            "export class FieldType {",
        ]
        for key, definition in registry.items():
            # Computed keys also support extension names containing punctuation.
            lines.append(
                f"    public static readonly [{json.dumps(key)}] = "
                f"new FieldTypeDefinition({json.dumps(definition.id)});"
            )
        lines.extend(["}", ""])
        options["output"].write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(f"Generated {len(registry.values())} field types")
