"""Generate functionality-specific Bloomerp test-case skeletons."""

from __future__ import annotations

import importlib
import inspect
import re
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Callable, Iterable

from django import forms
from django.apps import AppConfig, apps
from django.core.management.base import BaseCommand, CommandError
from django.db import models


GENERATED_FILE_HEADER = "# Generated by manage.py generate_test_cases.\n"
SUPPORTED_FUNCTIONALITIES = (
    "views",
    "components",
    "models",
    "widgets",
    "workflow_nodes",
    "dataviews",
    "model_fields",
)


@dataclass(frozen=True)
class GeneratedTestCase:
    """A generated test module waiting to be written."""

    functionality: str
    target: Path
    content: str


class Command(BaseCommand):
    help = "Generate functionality-specific Bloomerp test-case skeletons."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "apps",
            nargs="+",
            help="Django app labels or dotted app names to generate tests for.",
        )
        parser.add_argument(
            "--functionality",
            default=",".join(SUPPORTED_FUNCTIONALITIES),
            help=(
                "Comma-separated functionality list. Choices: "
                + ", ".join(SUPPORTED_FUNCTIONALITIES)
            ),
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Overwrite existing generated target files.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print planned changes without writing files.",
        )

    def handle(self, *args, **options) -> None:
        selected_functionalities = self._parse_functionalities(
            options["functionality"]
        )
        app_configs = [self._resolve_app_config(value) for value in options["apps"]]
        working_directory = Path.cwd().resolve()

        generated: list[GeneratedTestCase] = []
        for app_config in app_configs:
            self._validate_local_app(app_config, working_directory)
            for functionality in selected_functionalities:
                generated.extend(self._discover(app_config, functionality))

        generated = self._deduplicate_targets(generated)
        created = overwritten = skipped = 0
        for test_case in generated:
            action = self._write_test_case(
                test_case,
                force=options["force"],
                dry_run=options["dry_run"],
            )
            if action == "created":
                created += 1
            elif action == "overwritten":
                overwritten += 1
            else:
                skipped += 1

        qualifier = "Would generate" if options["dry_run"] else "Generated"
        self.stdout.write(
            self.style.SUCCESS(
                f"{qualifier} {created + overwritten} test case(s); "
                f"skipped {skipped} existing file(s)."
            )
        )

    def _parse_functionalities(self, raw_value: str) -> tuple[str, ...]:
        """Normalize and validate the requested functionality list."""
        values = tuple(
            dict.fromkeys(
                value.strip().lower().replace("-", "_")
                for value in raw_value.split(",")
                if value.strip()
            )
        )
        if values == ("all",):
            return SUPPORTED_FUNCTIONALITIES
        if not values:
            raise CommandError("Provide at least one functionality.")

        invalid = sorted(set(values) - set(SUPPORTED_FUNCTIONALITIES))
        if invalid:
            raise CommandError(
                f"Unsupported functionality: {', '.join(invalid)}. "
                f"Choose from: {', '.join(SUPPORTED_FUNCTIONALITIES)}."
            )
        return values

    def _resolve_app_config(self, value: str) -> AppConfig:
        """Resolve either an app label or its dotted Django name."""
        try:
            return apps.get_app_config(value)
        except LookupError:
            matches = [config for config in apps.get_app_configs() if config.name == value]
            if len(matches) == 1:
                return matches[0]
        raise CommandError(f"Unknown Django app {value!r}.")

    def _validate_local_app(
        self, app_config: AppConfig, working_directory: Path
    ) -> None:
        """Reject installed apps whose source is outside the working directory."""
        app_path = Path(app_config.path).resolve()
        try:
            app_path.relative_to(working_directory)
        except ValueError as exc:
            raise CommandError(
                f"App {app_config.label!r} is outside the working directory: {app_path}"
            ) from exc

    def _discover(
        self, app_config: AppConfig, functionality: str
    ) -> list[GeneratedTestCase]:
        """Dispatch discovery for one app and functionality."""
        discoverer = getattr(self, f"_discover_{functionality}")
        return discoverer(app_config)

    def _discover_views(self, app_config: AppConfig) -> list[GeneratedTestCase]:
        return self._discover_routes(app_config, components=False)

    def _discover_components(
        self, app_config: AppConfig
    ) -> list[GeneratedTestCase]:
        return self._discover_routes(app_config, components=True)

    def _discover_routes(
        self, app_config: AppConfig, *, components: bool
    ) -> list[GeneratedTestCase]:
        """Generate one test class per unique routed callable."""
        from bloomerp.router import RouteType, router

        grouped_routes: dict[tuple[str, int, str], list] = {}
        callables: dict[tuple[str, int, str], Callable] = {}
        for route in router.get_routes_by_app(app_config):
            is_component = (
                route.path.lstrip("/").startswith("components/")
                or route.url_name.startswith("components_")
            )
            if is_component != components:
                continue
            if not components and route.route_type in {
                RouteType.API,
                RouteType.API_MODEL,
                RouteType.API_DETAIL,
                RouteType.WEBSOCKET,
            }:
                continue

            routed_callable = inspect.unwrap(route.view)
            source_definition = self._source_definition(routed_callable)
            source = self._source_path(source_definition)
            try:
                source_line = inspect.getsourcelines(source_definition)[1]
            except (OSError, TypeError):
                source_line = 0
            key = (
                str(source),
                source_line,
                getattr(
                    source_definition,
                    "__qualname__",
                    source_definition.__name__,
                ),
            )
            grouped_routes.setdefault(key, []).append(route)
            callables[key] = source_definition

        functionality = "components" if components else "views"
        suffix = "component" if components else "view"
        route_sources = {
            key: self._source_path(callables[key]) for key in grouped_routes
        }
        provisional_targets = {
            key: self._nested_target(
                app_config,
                functionality,
                route_sources[key],
                source_root=functionality,
                filename=(
                    f"test_{_suffixed_snake(_definition_name(callables[key]), suffix)}.py"
                ),
            )
            for key in grouped_routes
        }
        results = []
        for key in sorted(grouped_routes):
            routed_callable = callables[key]
            routes = sorted(grouped_routes[key], key=lambda route: route.url_name)
            source = route_sources[key]
            normalized_name = _snake_case(_definition_name(routed_callable))
            collision = list(provisional_targets.values()).count(
                provisional_targets[key]
            ) > 1
            callable_kind = "class" if inspect.isclass(routed_callable) else "function"
            source_hint = _snake_case(source.stem)
            disambiguator = (
                f"_{source_hint}_{callable_kind}" if collision else ""
            )
            target = self._nested_target(
                app_config,
                functionality,
                source,
                source_root=functionality,
                filename=(
                    f"test_{_suffixed_snake(normalized_name + disambiguator, suffix)}.py"
                ),
            )
            kind_suffix = (
                f"{_pascal_case(source.stem)}{callable_kind.title()}"
                if collision
                else ""
            )
            class_name = "Test" + _suffixed_pascal(
                f"{_definition_name(routed_callable)}{kind_suffix}", suffix
            )
            route_types = {route.route_type for route in routes}
            if len(route_types) != 1:
                raise CommandError(
                    f"View {routed_callable!r} is registered with multiple route types."
                )
            route_type = route_types.pop()
            imports: list[tuple[str, str]] = []
            attributes: list[tuple[str, str]] = []
            if components:
                base_class = "BloomerpComponentTestCase"
                view_name = routes[0].url_name
            else:
                base_classes = {
                    RouteType.APP: "BloomerpViewTestCase",
                    RouteType.MODEL: "BloomerpModelViewTestCase",
                    RouteType.DETAIL: "BloomerpDetailViewTestCase",
                    RouteType.MODULE: "BloomerpModuleViewTestCase",
                }
                base_class = base_classes[route_type]
                view_name_counts: dict[str, int] = {}
                for route in routes:
                    registered_name = route.base_url_name or route.url_name
                    view_name_counts[registered_name] = (
                        view_name_counts.get(registered_name, 0) + 1
                    )
                view_name = sorted(
                    view_name_counts,
                    key=lambda name: (-view_name_counts[name], name),
                )[0]
                selected_routes = [
                    route
                    for route in routes
                    if (route.base_url_name or route.url_name) == view_name
                ]

                if route_type in {RouteType.MODEL, RouteType.DETAIL}:
                    route_models = sorted(
                        {
                            route.model
                            for route in selected_routes
                            if route.model is not None
                        },
                        key=lambda model: (model.__module__, model.__name__),
                    )
                    model_value = "None"
                    if len(route_models) == 1:
                        route_model = route_models[0]
                        imports.append((route_model.__module__, route_model.__name__))
                        model_value = route_model.__name__
                    attributes.append(("model", model_value))

                if route_type == RouteType.MODULE:
                    route_modules = {
                        (route.module.full_id or route.module.id)
                        for route in selected_routes
                        if route.module is not None
                    }
                    module_value = (
                        repr(next(iter(route_modules)))
                        if len(route_modules) == 1
                        else "None"
                    )
                    attributes.append(("module", module_value))

            content = self._render_request_test(
                base_class=base_class,
                class_name=class_name,
                view_name=view_name,
                imports=imports,
                attributes=attributes,
            )
            results.append(GeneratedTestCase(functionality, target, content))
        return results

    def _discover_models(self, app_config: AppConfig) -> list[GeneratedTestCase]:
        results = []
        for model in sorted(app_config.get_models(), key=lambda item: item.__name__):
            source = self._source_path(model)
            target = self._nested_target(
                app_config,
                "models",
                source,
                source_root="models",
                filename=f"test_{_suffixed_snake(model.__name__, 'model')}.py",
            )
            content = self._render_class_attribute_test(
                import_path=model.__module__,
                imported_name=model.__name__,
                base_class="BloomerpModelTestCase",
                class_name="Test" + _suffixed_pascal(model.__name__, "model"),
                attribute_name="model",
                attribute_value=model.__name__,
            )
            results.append(GeneratedTestCase("models", target, content))
        return results

    def _discover_widgets(self, app_config: AppConfig) -> list[GeneratedTestCase]:
        return self._discover_subclasses(
            app_config,
            source_root="widgets",
            functionality="widgets",
            parent_class=forms.Widget,
            base_class="BloomerpWidgetTestCase",
            attribute_name="widget_class",
            filename_suffix="widget",
        )

    def _discover_model_fields(
        self, app_config: AppConfig
    ) -> list[GeneratedTestCase]:
        return self._discover_subclasses(
            app_config,
            source_root="model_fields",
            functionality="model_fields",
            parent_class=models.Field,
            base_class="BloomerpModelFieldTestCase",
            attribute_name="field_class",
            filename_suffix="field",
        )

    def _discover_subclasses(
        self,
        app_config: AppConfig,
        *,
        source_root: str,
        functionality: str,
        parent_class: type,
        base_class: str,
        attribute_name: str,
        filename_suffix: str,
    ) -> list[GeneratedTestCase]:
        """Discover app-owned subclasses declared below a source package."""
        results = []
        for module in self._import_source_modules(app_config, source_root):
            for _, implementation in inspect.getmembers(module, inspect.isclass):
                if implementation.__module__ != module.__name__:
                    continue
                if implementation is parent_class or not issubclass(
                    implementation, parent_class
                ):
                    continue
                source = self._source_path(implementation)
                target = self._nested_target(
                    app_config,
                    functionality,
                    source,
                    source_root=source_root,
                    filename=(
                        f"test_{_suffixed_snake(implementation.__name__, filename_suffix)}.py"
                    ),
                )
                content = self._render_class_attribute_test(
                    import_path=implementation.__module__,
                    imported_name=implementation.__name__,
                    base_class=base_class,
                    class_name=(
                        "Test"
                        + _suffixed_pascal(
                            implementation.__name__, filename_suffix
                        )
                    ),
                    attribute_name=attribute_name,
                    attribute_value=implementation.__name__,
                )
                results.append(GeneratedTestCase(functionality, target, content))
        return results

    def _discover_workflow_nodes(
        self, app_config: AppConfig
    ) -> list[GeneratedTestCase]:
        from bloomerp.automation.registry import WORKFLOW_NODE_REGISTRY

        results = []
        for definition in WORKFLOW_NODE_REGISTRY.values():
            implementation = definition.executor_cls
            if implementation is None or not self._belongs_to_app(
                implementation, app_config
            ):
                continue
            normalized_name = _suffixed_snake(definition.id, "node")
            target = (
                Path(app_config.path)
                / "tests"
                / "automation"
                / "nodes"
                / f"test_{normalized_name}.py"
            )
            class_name = "Test" + _suffixed_pascal(definition.id, "node")
            content = (
                GENERATED_FILE_HEADER
                + f"from {implementation.__module__} import {implementation.__name__}\n"
                + "from bloomerp.tests.base import (\n"
                + "    BloomerpWorkflowNodeTestCase,\n"
                + "    WorkflowSimulation,\n"
                + ")\n\n\n"
                + f"class {class_name}(BloomerpWorkflowNodeTestCase):\n"
                + f"    node_id = {definition.id!r}\n"
                + f"    executor_class = {implementation.__name__}\n\n"
                + "    def get_simulations(self) -> list[WorkflowSimulation]:\n"
                + "        return []\n"
            )
            results.append(GeneratedTestCase("workflow_nodes", target, content))
        return results

    def _discover_dataviews(self, app_config: AppConfig) -> list[GeneratedTestCase]:
        from bloomerp.dataviews.registry import DATAVIEW_REGISTRY

        results = []
        for key, definition in DATAVIEW_REGISTRY.items():
            implementations = (definition.renderer_cls, definition.config_cls)
            if not any(
                self._belongs_to_app(implementation, app_config)
                for implementation in implementations
            ):
                continue
            normalized_name = _suffixed_snake(key, "dataview")
            target = (
                Path(app_config.path)
                / "tests"
                / "dataviews"
                / f"test_{normalized_name}.py"
            )
            class_name = "Test" + _suffixed_pascal(key, "dataview")
            content = (
                GENERATED_FILE_HEADER
                + "from bloomerp.tests.base import BloomerpDataviewTestCase\n\n\n"
                + f"class {class_name}(BloomerpDataviewTestCase):\n"
                + f"    dataview_key = {key!r}\n"
            )
            results.append(GeneratedTestCase("dataviews", target, content))
        return results

    def _belongs_to_app(self, implementation: type, app_config: AppConfig) -> bool:
        """Infer registry ownership from an implementation class's module."""
        owner = apps.get_containing_app_config(implementation.__module__)
        return owner is not None and owner.label == app_config.label

    def _import_source_modules(
        self, app_config: AppConfig, source_root: str
    ) -> Iterable[ModuleType]:
        """Import Python modules declared below one app source directory."""
        source_directory = Path(app_config.path) / source_root
        if not source_directory.is_dir():
            return []

        modules = []
        for source in sorted(source_directory.rglob("*.py")):
            if "__pycache__" in source.parts:
                continue
            relative = source.relative_to(Path(app_config.path)).with_suffix("")
            module_parts = list(relative.parts)
            if module_parts[-1] == "__init__":
                module_parts.pop()
            module_name = ".".join([app_config.name, *module_parts])
            try:
                modules.append(importlib.import_module(module_name))
            except Exception as exc:
                raise CommandError(f"Unable to import {module_name}: {exc}") from exc
        return modules

    def _source_path(self, implementation: Callable | type) -> Path:
        """Return the concrete source file for a discovered implementation."""
        source = inspect.getsourcefile(implementation)
        if source is None:
            raise CommandError(f"Cannot determine source for {implementation!r}.")
        return Path(source).resolve()

    def _source_definition(self, implementation: Callable | type) -> Callable | type:
        """Resolve generated view subclasses to their nearest source-defined base."""
        if not inspect.isclass(implementation):
            return implementation

        for candidate in implementation.__mro__:
            try:
                inspect.getsourcelines(candidate)
            except (OSError, TypeError):
                continue
            return candidate
        return implementation

    def _nested_target(
        self,
        app_config: AppConfig,
        functionality: str,
        source: Path,
        *,
        source_root: str,
        filename: str,
    ) -> Path:
        """Mirror directories below a functionality's source root into tests."""
        app_path = Path(app_config.path).resolve()
        try:
            relative_source = source.relative_to(app_path)
        except ValueError as exc:
            raise CommandError(
                f"Source {source} is outside app {app_config.label!r}."
            ) from exc

        parts = relative_source.parts
        nested_parts: tuple[str, ...] = ()
        if source_root in parts:
            root_index = parts.index(source_root)
            nested_parts = parts[root_index + 1 : -1]
        else:
            nested_parts = parts[:-1]
        return app_path / "tests" / functionality / Path(*nested_parts) / filename

    def _render_request_test(
        self,
        *,
        base_class: str,
        class_name: str,
        view_name: str,
        imports: list[tuple[str, str]] | None = None,
        attributes: list[tuple[str, str]] | None = None,
    ) -> str:
        specialized_request_setup_class = {
            "BloomerpDetailViewTestCase": "ModelRequestSetup",
            "BloomerpModelViewTestCase": "ModelRequestSetup",
            "BloomerpModuleViewTestCase": "ModuleRequestSetup",
        }.get(base_class)
        import_lines = [
            f"from {import_path} import {imported_name}"
            for import_path, imported_name in imports or []
        ]
        import_lines.extend(
            [
                "from bloomerp.tests.base import (",
                f"    {base_class},",
                "    ExpectedResult,",
                "    RequestSetup,",
                *(
                    [f"    {specialized_request_setup_class},"]
                    if specialized_request_setup_class
                    else []
                ),
                ")",
            ]
        )
        attribute_lines = [f"    view_name = {view_name!r}"]
        attribute_lines.extend(
            f"    {attribute_name} = {attribute_value}"
            for attribute_name, attribute_value in attributes or []
        )
        return "\n".join(
            [
                GENERATED_FILE_HEADER.rstrip(),
                *import_lines,
                "",
                "",
                f"class {class_name}({base_class}):",
                *attribute_lines,
                "",
                "    def get_request_setups(self) -> list[RequestSetup]:",
                "        # Add only the route scenarios this callable needs.",
                "        return []",
                "",
            ]
        )

    def _render_class_attribute_test(
        self,
        *,
        import_path: str,
        imported_name: str,
        base_class: str,
        class_name: str,
        attribute_name: str,
        attribute_value: str,
    ) -> str:
        return (
            GENERATED_FILE_HEADER
            + f"from {import_path} import {imported_name}\n"
            + f"from bloomerp.tests.base import {base_class}\n\n\n"
            + f"class {class_name}({base_class}):\n"
            + f"    {attribute_name} = {attribute_value}\n"
        )

    def _deduplicate_targets(
        self, generated: list[GeneratedTestCase]
    ) -> list[GeneratedTestCase]:
        """Deduplicate identical discoveries and reject filename collisions."""
        by_target: dict[Path, GeneratedTestCase] = {}
        for test_case in generated:
            existing = by_target.get(test_case.target)
            if existing is not None and existing.content != test_case.content:
                raise CommandError(
                    f"Multiple test cases resolve to {test_case.target}. "
                    "Rename one implementation to avoid the collision."
                )
            by_target[test_case.target] = test_case
        return [by_target[target] for target in sorted(by_target)]

    def _write_test_case(
        self,
        test_case: GeneratedTestCase,
        *,
        force: bool,
        dry_run: bool,
    ) -> str:
        """Create, overwrite, or skip one generated test module."""
        exists = test_case.target.exists()
        generated_target = (
            exists
            and test_case.target.read_text(encoding="utf-8").startswith(
                GENERATED_FILE_HEADER
            )
        )
        if exists and not force and not generated_target:
            self.stdout.write(f"Skipped existing {test_case.target}")
            return "skipped"

        action = "overwritten" if exists else "created"
        verb = "Would overwrite" if exists else "Would create"
        if dry_run:
            self.stdout.write(f"{verb} {test_case.target}")
            return action

        self._ensure_test_packages(test_case.target.parent)
        test_case.target.write_text(test_case.content, encoding="utf-8")
        self.stdout.write(f"{action.title()} {test_case.target}")
        return action

    def _ensure_test_packages(self, target_directory: Path) -> None:
        """Create target directories and missing Python package markers."""
        target_directory.mkdir(parents=True, exist_ok=True)
        current = target_directory
        while current.name != "tests":
            init_file = current / "__init__.py"
            if not init_file.exists():
                init_file.write_text("", encoding="utf-8")
            current = current.parent
        tests_init = current / "__init__.py"
        if not tests_init.exists():
            tests_init.write_text("", encoding="utf-8")


def _snake_case(value: str) -> str:
    """Normalize class, function, or registry names for Python filenames."""
    normalized = value.replace("-", "_").replace(" ", "_")
    normalized = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", normalized)
    return re.sub(r"_+", "_", normalized).strip("_").lower()


def _pascal_case(value: str) -> str:
    """Normalize class, function, or registry names for test classes."""
    return "".join(part.capitalize() for part in _snake_case(value).split("_"))


def _suffixed_snake(value: str, suffix: str) -> str:
    """Add a filename suffix unless the normalized name already contains it."""
    normalized = _snake_case(value)
    normalized_suffix = _snake_case(suffix)
    if normalized == normalized_suffix or normalized.endswith(f"_{normalized_suffix}"):
        return normalized
    return f"{normalized}_{normalized_suffix}"


def _suffixed_pascal(value: str, suffix: str) -> str:
    """Add a class-name suffix unless the normalized name already contains it."""
    normalized = _pascal_case(value)
    normalized_suffix = _pascal_case(suffix)
    if normalized.endswith(normalized_suffix):
        return normalized
    return f"{normalized}{normalized_suffix}"


def _definition_name(implementation: Callable | type) -> str:
    """Return the stable source-level name of a callable or class."""
    qualname = getattr(implementation, "__qualname__", implementation.__name__)
    return qualname.split(".")[-1]
