# Generated by manage.py generate_test_cases.
from bloomerp.models import FileFolder
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestDeleteFolderComponent(BloomerpComponentTestCase):
    """Tests function `delete_folder` from `bloomerp/components/files/actions/delete.py`."""

    view_name = "components_files_delete_folder"

    def get_request_setups(self) -> list[RequestSetup]:
        folder = FileFolder.objects.create(
            name="Disposable",
            created_by=self.admin_user,
            updated_by=self.admin_user,
        )
        view_kwargs = {"folder_id": folder.pk}

        return [
            RequestSetup(
                name="render delete-folder confirmation",
                user=self.admin_user,
                view_kwargs=view_kwargs,
            ),
            RequestSetup(
                name="delete folder",
                method="POST",
                user=self.admin_user,
                view_kwargs=view_kwargs,
                expected=ExpectedResult(
                    response_validators=[
                        self.header_equals("HX-Refresh", "true"),
                        self._folder_does_not_exist(folder.pk),
                    ],
                ),
            ),
        ]

    def _folder_does_not_exist(self, folder_id: int):
        return self._named_validator(
            f"folder_does_not_exist({folder_id!r})",
            lambda _response: not FileFolder.objects.filter(pk=folder_id).exists(),
        )
