# Generated by manage.py generate_test_cases.
from bloomerp.models import FileFolder
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRenameFolderComponent(BloomerpComponentTestCase):
    """Tests function `rename_folder` from `bloomerp/components/files/actions/rename.py`."""

    view_name = "components_files_rename_folder"

    def get_request_setups(self) -> list[RequestSetup]:
        folder = FileFolder.objects.create(
            name="Before",
            created_by=self.admin_user,
            updated_by=self.admin_user,
        )
        view_kwargs = {"folder_id": folder.pk}

        return [
            RequestSetup(
                name="render rename-folder form",
                user=self.admin_user,
                view_kwargs=view_kwargs,
            ),
            RequestSetup(
                name="rename folder",
                method="POST",
                user=self.admin_user,
                view_kwargs=view_kwargs,
                data={"name": "After"},
                expected=ExpectedResult(
                    response_validators=[
                        self.header_equals("HX-Refresh", "true"),
                        self._folder_has_name(folder.pk, "After"),
                    ],
                ),
            ),
        ]

    def _folder_has_name(self, folder_id: int, name: str):
        return self._named_validator(
            f"folder_has_name({folder_id!r}, {name!r})",
            lambda _response: FileFolder.objects.filter(
                pk=folder_id,
                name=name,
            ).exists(),
        )
