# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestFieldSelectorComponent(BloomerpComponentTestCase):
    """Tests function `field_selector` from `bloomerp/components/objects/dataviews/bulk_actions.py`."""

    view_name = 'components_bulk_actions_field_selector'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
