# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestUpdateDataviewPreferenceComponent(BloomerpComponentTestCase):
    """Tests function `update_dataview_preference` from `bloomerp/components/objects/dataviews/update_preference.py`."""

    view_name = 'components_update_dataview_preference'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
