# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestBulkActionsComponent(BloomerpComponentTestCase):
    view_name = 'components_bulk_actions'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
