# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestUpdateDataviewPreferenceComponent(BloomerpComponentTestCase):
    view_name = 'components_update_dataview_preference'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
