# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestKanbanMoveCardComponent(BloomerpComponentTestCase):
    """Tests function `kanban_move_card` from `bloomerp/components/objects/dataviews/kanban.py`."""

    view_name = 'components_kanban_move_card'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
