# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestConfiguredDataviewActionComponent(BloomerpComponentTestCase):
    """Tests function `configured_dataview_action` from `bloomerp/components/objects/dataviews/dataview_action.py`."""

    view_name = 'components_dataview_action'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
