# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestKanbanMoveCardComponent(BloomerpComponentTestCase):
    view_name = 'components_kanban_move_card'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
