# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBloomerpModuleWorkspaceView(BloomerpViewTestCase):
    """Tests class `BloomerpModuleWorkspace` from `bloomerp/views/workspaces/workspace.py`."""

    view_name = 'workspace'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
