# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.tile import Tile
from bloomerp.tests.base import (
    BloomerpDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestUpdateTileView(BloomerpDetailViewTestCase):
    view_name = 'Update Tile'
    model = Tile

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
