# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.workspace import Workspace
from bloomerp.tests.base import BloomerpModelViewTestCase


class TestCreateWorkspaceView(BloomerpModelViewTestCase):
    view_name = 'add'
    model = Workspace

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
