# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpModuleViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModuleRequestSetup,
)


class TestBloomerpModuleHomeView(BloomerpModuleViewTestCase):
    """Tests class `BloomerpModuleHomeView` from `bloomerp/views/workspaces/module_home.py`."""

    view_name = '{module}'
    module = None

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
