# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.tile import Tile
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestUpdateTileView(BloomerpDetailViewTestCase):
    view_name = 'Update Tile'
    model = Tile

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
