# Generated by manage.py generate_test_cases.
from bloomerp.models.workspaces.workspace import Workspace
from bloomerp.tests.base import (
    BloomerpModelViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestCreateWorkspaceView(BloomerpModelViewTestCase):
    """Tests class `CreateWorkspaceView` from `bloomerp/views/workspaces/create_workspace.py`."""

    view_name = 'add'
    model = Workspace

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
