# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpViewTestCase


class TestBloomerpHomeView(BloomerpViewTestCase):
    view_name = 'bloomerp_home_view'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
