# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpViewTestCase


class TestMyWorkspacesView(BloomerpViewTestCase):
    view_name = 'my_workspaces'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
