# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpModuleViewTestCase


class TestBloomerpModuleHomeView(BloomerpModuleViewTestCase):
    view_name = '{module}'
    module = None

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
