# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateTileView(BloomerpViewTestCase):
    """Tests class `CreateTileView` from `bloomerp/views/workspaces/create_tile.py`."""

    view_name = 'Create Tile'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
