# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow import Workflow
from bloomerp.tests.base import BloomerpDetailViewTestCase


class TestCreateWorkflowView(BloomerpDetailViewTestCase):
    view_name = 'builder'
    model = Workflow

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
