# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSidebarSetSelectedComponent(BloomerpComponentTestCase):
    """Tests function `sidebar_set_selected` from `bloomerp/components/ui/sidebar.py`."""

    view_name = 'components_workspaces_sidebar_set_selected'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
