# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestSidebarCreateComponent(BloomerpComponentTestCase):
    """Tests function `sidebar_create` from `bloomerp/components/ui/sidebar.py`."""

    view_name = 'components_workspaces_sidebar_create'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
