# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBloomerpOpenApischemaView(BloomerpAPIViewTestCase):
    """Tests class `BloomerpOpenAPISchemaView` from `bloomerp/views/api/docs/schema.py`."""

    view_name = 'schema'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
