# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestBloomerpRedocSchemaView(BloomerpAPIViewTestCase):
    """Tests class `BloomerpRedocSchemaView` from `bloomerp/views/api/docs/schema_ui.py`."""

    view_name = 'schema_ui'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
