# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestLoginView(BloomerpAPIViewTestCase):
    """Tests class `LoginView` from `bloomerp/views/api/auth/login.py`."""

    view_name = 'api_login'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
