# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestRegisterView(BloomerpAPIViewTestCase):
    """Tests class `RegisterView` from `bloomerp/views/api/auth/register.py`."""

    view_name = 'api_register'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
