# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpAPIViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCsrfView(BloomerpAPIViewTestCase):
    """Tests class `CsrfView` from `bloomerp/views/api/auth/csrf.py`."""

    view_name = 'csrf'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
