# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow import Workflow
from bloomerp.tests.base import (
    BloomerpAPIDetailViewTestCase,
    ExpectedResult,
    RequestSetup,
    ModelRequestSetup,
)


class TestWorkflowWebhookView(BloomerpAPIDetailViewTestCase):
    """Tests function `workflow_webhook` from `bloomerp/views/api/workflows/webhook.py`."""

    view_name = 'api_workflow_webhook'
    model = Workflow

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
