# Generated by manage.py generate_test_cases.
from bloomerp.models.api.api_key import ApiKey
from bloomerp.tests.base import BloomerpModelTestCase


class TestApiKeyModel(BloomerpModelTestCase):
    model = ApiKey
