# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpViewTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestTestView(BloomerpViewTestCase):
    """Tests class `TestView` from `bloomerp/views/test_view.py`."""

    view_name = 'testview'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
