# Generated by manage.py generate_test_cases.
from bloomerp.widgets.foreign_field_widget import ForeignFieldWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestForeignFieldWidget(BloomerpWidgetTestCase):
    widget_class = ForeignFieldWidget
