# Generated by manage.py generate_test_cases.
from bloomerp.widgets.code_editor_widget import CodeEditorWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestCodeEditorWidget(BloomerpWidgetTestCase):
    widget_class = CodeEditorWidget
