# Generated by manage.py generate_test_cases.
from bloomerp.widgets.object_files_widget import ObjectFilesWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestObjectFilesWidget(BloomerpWidgetTestCase):
    widget_class = ObjectFilesWidget
