# Generated by manage.py generate_test_cases.
from bloomerp.widgets.phone_number_widget import PhoneNumberWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestPhoneNumberWidget(BloomerpWidgetTestCase):
    widget_class = PhoneNumberWidget
