# Generated by manage.py generate_test_cases.
from bloomerp.widgets.ordered_field_select_widget import OrderedFieldSelectWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestOrderedFieldSelectWidget(BloomerpWidgetTestCase):
    widget_class = OrderedFieldSelectWidget
