# Generated by manage.py generate_test_cases.
from bloomerp.widgets.list_filter_widget import ListFilterWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestListFilterWidget(BloomerpWidgetTestCase):
    widget_class = ListFilterWidget
