# Generated by manage.py generate_test_cases.
from bloomerp.widgets.text_editor import BloomerpTextEditorWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestBloomerpTextEditorWidget(BloomerpWidgetTestCase):
    widget_class = BloomerpTextEditorWidget
