# Generated by manage.py generate_test_cases.
from bloomerp.widgets.datalist_widget import DatalistTextInput
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestDatalistTextInputWidget(BloomerpWidgetTestCase):
    widget_class = DatalistTextInput
