# Generated by manage.py generate_test_cases.
from bloomerp.widgets.select_widget import InputSelectWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestInputSelectWidget(BloomerpWidgetTestCase):
    widget_class = InputSelectWidget
