# Generated by manage.py generate_test_cases.
from bloomerp.widgets.week_widget import WeekWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestWeekWidget(BloomerpWidgetTestCase):
    widget_class = WeekWidget
