# Generated by manage.py generate_test_cases.
from bloomerp.widgets.file_field_widget import BloomerpFileFieldWidget
from bloomerp.tests.base import BloomerpWidgetTestCase


class TestBloomerpFileFieldWidget(BloomerpWidgetTestCase):
    widget_class = BloomerpFileFieldWidget
