# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestPreviewPermissionsTableComponent(BloomerpComponentTestCase):
    """Tests function `preview_permissions_table` from `bloomerp/components/access_control/preview_permissions_table.py`."""

    view_name = 'components_preview_permissions_table'

    def get_request_setups(self) -> list[RequestSetup]:
        # Add only the route scenarios this callable needs.
        return []
