# Generated by manage.py generate_test_cases.
from bloomerp.tests.base import BloomerpComponentTestCase


class TestPreviewPermissionsTableComponent(BloomerpComponentTestCase):
    view_name = 'components_preview_permissions_table'

    def get_request_setups(self):
        # Add only the route scenarios this callable needs.
        return []
