# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_run import WorkflowRun
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkflowRunModel(BloomerpModelTestCase):
    model = WorkflowRun
