# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_node import WorkflowNode
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkflowNodeModel(BloomerpModelTestCase):
    model = WorkflowNode
