# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow import Workflow
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkflowModel(BloomerpModelTestCase):
    model = Workflow
