# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_edge import WorkflowEdge
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkflowEdgeModel(BloomerpModelTestCase):
    model = WorkflowEdge
