# Generated by manage.py generate_test_cases.
from bloomerp.models.automation.workflow_run_step import WorkflowRunStep
from bloomerp.tests.base import BloomerpModelTestCase


class TestWorkflowRunStepModel(BloomerpModelTestCase):
    model = WorkflowRunStep
