# Generated by manage.py generate_test_cases.
from types import SimpleNamespace

from django.urls import reverse

from bloomerp.models import FileFolder
from bloomerp.models.files.file import _create_folder_endpoint
from bloomerp.tests.base import (
    BloomerpComponentTestCase,
    ExpectedResult,
    RequestSetup,
)


class TestCreateFolderComponent(BloomerpComponentTestCase):
    """Tests function `create_folder` from `bloomerp/components/files/folders/create.py`."""

    view_name = "components_create_folder"

    def get_request_setups(self) -> list[RequestSetup]:
        parent = FileFolder.objects.create(
            name="Parent",
            created_by=self.admin_user,
            updated_by=self.admin_user,
        )
        url = reverse(self.view_name)

        return [
            RequestSetup(
                name="render create-folder form",
                user=self.admin_user,
                expected=ExpectedResult(
                    response_validators=[
                        self.contains_text(f'action="{url}"'),
                        self.contains_text('name="name"'),
                    ],
                ),
            ),
            RequestSetup(
                name="create root folder",
                method="POST",
                user=self.admin_user,
                data={"name": "Contracts"},
                expected=ExpectedResult(
                    response_validators=[
                        self.header_equals("HX-Refresh", "true"),
                        self._folder_exists(
                            name="Contracts",
                            parent=None,
                            created_by=self.admin_user,
                        ),
                    ],
                ),
            ),
            RequestSetup(
                name="create child folder",
                method="POST",
                user=self.admin_user,
                data={"name": "Child", "folder_id": parent.pk},
                expected=ExpectedResult(
                    response_validators=self._folder_exists(
                        name="Child",
                        parent=parent,
                    ),
                ),
            ),
            RequestSetup(
                name="reject user without add-folder permission",
                method="POST",
                user=self.normal_user,
                data={"name": "Forbidden"},
                expected=ExpectedResult(
                    status_code=403,
                    response_validators=self._folder_does_not_exist("Forbidden"),
                ),
            ),
        ]

    def test_dataview_action_preserves_browser_querystring(self) -> None:
        endpoint = _create_folder_endpoint(
            SimpleNamespace(querystring="folder=12&object_id=34")
        )

        self.assertEqual(
            endpoint,
            f"{reverse(self.view_name)}?folder=12&object_id=34",
        )

    def _folder_exists(
        self,
        *,
        name: str,
        parent: FileFolder | None,
        created_by=None,
    ):
        filters = {"name": name, "parent": parent}
        if created_by is not None:
            filters["created_by"] = created_by
        return self._named_validator(
            f"folder_exists({filters!r})",
            lambda _response: FileFolder.objects.filter(**filters).exists(),
        )

    def _folder_does_not_exist(self, name: str):
        return self._named_validator(
            f"folder_does_not_exist({name!r})",
            lambda _response: not FileFolder.objects.filter(name=name).exists(),
        )
